package gobject

/*
#include <glib-object.h>
#include <gobject/gvaluecollector.h>
#include <stdlib.h>

gint __G_PARAM_MASK = G_PARAM_MASK;
gint __G_PARAM_STATIC_STRINGS = G_PARAM_STATIC_STRINGS;
gint __G_PARAM_USER_SHIFT = G_PARAM_USER_SHIFT;
gint __G_SIGNAL_FLAGS_MASK = G_SIGNAL_FLAGS_MASK;
gint __G_SIGNAL_MATCH_MASK = G_SIGNAL_MATCH_MASK;
GType __G_TYPE_FLAG_RESERVED_ID_BIT = G_TYPE_FLAG_RESERVED_ID_BIT;
gint __G_TYPE_FUNDAMENTAL_MAX = G_TYPE_FUNDAMENTAL_MAX;
gint __G_TYPE_FUNDAMENTAL_SHIFT = G_TYPE_FUNDAMENTAL_SHIFT;
gint __G_TYPE_RESERVED_BSE_FIRST = G_TYPE_RESERVED_BSE_FIRST;
gint __G_TYPE_RESERVED_BSE_LAST = G_TYPE_RESERVED_BSE_LAST;
gint __G_TYPE_RESERVED_GLIB_FIRST = G_TYPE_RESERVED_GLIB_FIRST;
gint __G_TYPE_RESERVED_GLIB_LAST = G_TYPE_RESERVED_GLIB_LAST;
gint __G_TYPE_RESERVED_USER_FIRST = G_TYPE_RESERVED_USER_FIRST;
gint __G_VALUE_COLLECT_FORMAT_MAX_LENGTH = G_VALUE_COLLECT_FORMAT_MAX_LENGTH;
gint __G_VALUE_NOCOPY_CONTENTS = G_VALUE_NOCOPY_CONTENTS;
*/
import "C"

var (
	PARAM_MASK                      = C.__G_PARAM_MASK
	PARAM_STATIC_STRINGS            = C.__G_PARAM_STATIC_STRINGS
	PARAM_USER_SHIFT                = C.__G_PARAM_USER_SHIFT
	SIGNAL_FLAGS_MASK               = C.__G_SIGNAL_FLAGS_MASK
	SIGNAL_MATCH_MASK               = C.__G_SIGNAL_MATCH_MASK
	TYPE_FLAG_RESERVED_ID_BIT       = C.__G_TYPE_FLAG_RESERVED_ID_BIT
	TYPE_FUNDAMENTAL_MAX            = C.__G_TYPE_FUNDAMENTAL_MAX
	TYPE_FUNDAMENTAL_SHIFT          = C.__G_TYPE_FUNDAMENTAL_SHIFT
	TYPE_RESERVED_BSE_FIRST         = C.__G_TYPE_RESERVED_BSE_FIRST
	TYPE_RESERVED_BSE_LAST          = C.__G_TYPE_RESERVED_BSE_LAST
	TYPE_RESERVED_GLIB_FIRST        = C.__G_TYPE_RESERVED_GLIB_FIRST
	TYPE_RESERVED_GLIB_LAST         = C.__G_TYPE_RESERVED_GLIB_LAST
	TYPE_RESERVED_USER_FIRST        = C.__G_TYPE_RESERVED_USER_FIRST
	VALUE_COLLECT_FORMAT_MAX_LENGTH = C.__G_VALUE_COLLECT_FORMAT_MAX_LENGTH
	VALUE_NOCOPY_CONTENTS           = C.__G_VALUE_NOCOPY_CONTENTS
)
