package gdk

/*
#include <gdk/gdk.h>
#include <gdk/gdkprivate.h>
#include <glib.h>
#include <stdlib.h>
*/
import "C"

var (
	// AxisUse
	AXIS_IGNORE   = C.GdkAxisUse(C.GDK_AXIS_IGNORE)
	AXIS_X        = C.GdkAxisUse(C.GDK_AXIS_X)
	AXIS_Y        = C.GdkAxisUse(C.GDK_AXIS_Y)
	AXIS_PRESSURE = C.GdkAxisUse(C.GDK_AXIS_PRESSURE)
	AXIS_XTILT    = C.GdkAxisUse(C.GDK_AXIS_XTILT)
	AXIS_YTILT    = C.GdkAxisUse(C.GDK_AXIS_YTILT)
	AXIS_WHEEL    = C.GdkAxisUse(C.GDK_AXIS_WHEEL)
	AXIS_LAST     = C.GdkAxisUse(C.GDK_AXIS_LAST)

	// ByteOrder
	LSB_FIRST = C.GdkByteOrder(C.GDK_LSB_FIRST)
	MSB_FIRST = C.GdkByteOrder(C.GDK_MSB_FIRST)

	// CrossingMode
	CROSSING_NORMAL        = C.GdkCrossingMode(C.GDK_CROSSING_NORMAL)
	CROSSING_GRAB          = C.GdkCrossingMode(C.GDK_CROSSING_GRAB)
	CROSSING_UNGRAB        = C.GdkCrossingMode(C.GDK_CROSSING_UNGRAB)
	CROSSING_GTK_GRAB      = C.GdkCrossingMode(C.GDK_CROSSING_GTK_GRAB)
	CROSSING_GTK_UNGRAB    = C.GdkCrossingMode(C.GDK_CROSSING_GTK_UNGRAB)
	CROSSING_STATE_CHANGED = C.GdkCrossingMode(C.GDK_CROSSING_STATE_CHANGED)
	CROSSING_TOUCH_BEGIN   = C.GdkCrossingMode(C.GDK_CROSSING_TOUCH_BEGIN)
	CROSSING_TOUCH_END     = C.GdkCrossingMode(C.GDK_CROSSING_TOUCH_END)
	CROSSING_DEVICE_SWITCH = C.GdkCrossingMode(C.GDK_CROSSING_DEVICE_SWITCH)

	// CursorType
	X_CURSOR            = C.GdkCursorType(C.GDK_X_CURSOR)
	ARROW               = C.GdkCursorType(C.GDK_ARROW)
	BASED_ARROW_DOWN    = C.GdkCursorType(C.GDK_BASED_ARROW_DOWN)
	BASED_ARROW_UP      = C.GdkCursorType(C.GDK_BASED_ARROW_UP)
	BOAT                = C.GdkCursorType(C.GDK_BOAT)
	BOGOSITY            = C.GdkCursorType(C.GDK_BOGOSITY)
	BOTTOM_LEFT_CORNER  = C.GdkCursorType(C.GDK_BOTTOM_LEFT_CORNER)
	BOTTOM_RIGHT_CORNER = C.GdkCursorType(C.GDK_BOTTOM_RIGHT_CORNER)
	BOTTOM_SIDE         = C.GdkCursorType(C.GDK_BOTTOM_SIDE)
	BOTTOM_TEE          = C.GdkCursorType(C.GDK_BOTTOM_TEE)
	BOX_SPIRAL          = C.GdkCursorType(C.GDK_BOX_SPIRAL)
	CENTER_PTR          = C.GdkCursorType(C.GDK_CENTER_PTR)
	CIRCLE              = C.GdkCursorType(C.GDK_CIRCLE)
	CLOCK               = C.GdkCursorType(C.GDK_CLOCK)
	COFFEE_MUG          = C.GdkCursorType(C.GDK_COFFEE_MUG)
	CROSS               = C.GdkCursorType(C.GDK_CROSS)
	CROSS_REVERSE       = C.GdkCursorType(C.GDK_CROSS_REVERSE)
	CROSSHAIR           = C.GdkCursorType(C.GDK_CROSSHAIR)
	DIAMOND_CROSS       = C.GdkCursorType(C.GDK_DIAMOND_CROSS)
	DOT                 = C.GdkCursorType(C.GDK_DOT)
	DOTBOX              = C.GdkCursorType(C.GDK_DOTBOX)
	DOUBLE_ARROW        = C.GdkCursorType(C.GDK_DOUBLE_ARROW)
	DRAFT_LARGE         = C.GdkCursorType(C.GDK_DRAFT_LARGE)
	DRAFT_SMALL         = C.GdkCursorType(C.GDK_DRAFT_SMALL)
	DRAPED_BOX          = C.GdkCursorType(C.GDK_DRAPED_BOX)
	EXCHANGE            = C.GdkCursorType(C.GDK_EXCHANGE)
	FLEUR               = C.GdkCursorType(C.GDK_FLEUR)
	GOBBLER             = C.GdkCursorType(C.GDK_GOBBLER)
	GUMBY               = C.GdkCursorType(C.GDK_GUMBY)
	HAND1               = C.GdkCursorType(C.GDK_HAND1)
	HAND2               = C.GdkCursorType(C.GDK_HAND2)
	HEART               = C.GdkCursorType(C.GDK_HEART)
	ICON                = C.GdkCursorType(C.GDK_ICON)
	IRON_CROSS          = C.GdkCursorType(C.GDK_IRON_CROSS)
	LEFT_PTR            = C.GdkCursorType(C.GDK_LEFT_PTR)
	LEFT_SIDE           = C.GdkCursorType(C.GDK_LEFT_SIDE)
	LEFT_TEE            = C.GdkCursorType(C.GDK_LEFT_TEE)
	LEFTBUTTON          = C.GdkCursorType(C.GDK_LEFTBUTTON)
	LL_ANGLE            = C.GdkCursorType(C.GDK_LL_ANGLE)
	LR_ANGLE            = C.GdkCursorType(C.GDK_LR_ANGLE)
	MAN                 = C.GdkCursorType(C.GDK_MAN)
	MIDDLEBUTTON        = C.GdkCursorType(C.GDK_MIDDLEBUTTON)
	MOUSE               = C.GdkCursorType(C.GDK_MOUSE)
	PENCIL              = C.GdkCursorType(C.GDK_PENCIL)
	PIRATE              = C.GdkCursorType(C.GDK_PIRATE)
	PLUS                = C.GdkCursorType(C.GDK_PLUS)
	QUESTION_ARROW      = C.GdkCursorType(C.GDK_QUESTION_ARROW)
	RIGHT_PTR           = C.GdkCursorType(C.GDK_RIGHT_PTR)
	RIGHT_SIDE          = C.GdkCursorType(C.GDK_RIGHT_SIDE)
	RIGHT_TEE           = C.GdkCursorType(C.GDK_RIGHT_TEE)
	RIGHTBUTTON         = C.GdkCursorType(C.GDK_RIGHTBUTTON)
	RTL_LOGO            = C.GdkCursorType(C.GDK_RTL_LOGO)
	SAILBOAT            = C.GdkCursorType(C.GDK_SAILBOAT)
	SB_DOWN_ARROW       = C.GdkCursorType(C.GDK_SB_DOWN_ARROW)
	SB_H_DOUBLE_ARROW   = C.GdkCursorType(C.GDK_SB_H_DOUBLE_ARROW)
	SB_LEFT_ARROW       = C.GdkCursorType(C.GDK_SB_LEFT_ARROW)
	SB_RIGHT_ARROW      = C.GdkCursorType(C.GDK_SB_RIGHT_ARROW)
	SB_UP_ARROW         = C.GdkCursorType(C.GDK_SB_UP_ARROW)
	SB_V_DOUBLE_ARROW   = C.GdkCursorType(C.GDK_SB_V_DOUBLE_ARROW)
	SHUTTLE             = C.GdkCursorType(C.GDK_SHUTTLE)
	SIZING              = C.GdkCursorType(C.GDK_SIZING)
	SPIDER              = C.GdkCursorType(C.GDK_SPIDER)
	SPRAYCAN            = C.GdkCursorType(C.GDK_SPRAYCAN)
	STAR                = C.GdkCursorType(C.GDK_STAR)
	TARGET              = C.GdkCursorType(C.GDK_TARGET)
	TCROSS              = C.GdkCursorType(C.GDK_TCROSS)
	TOP_LEFT_ARROW      = C.GdkCursorType(C.GDK_TOP_LEFT_ARROW)
	TOP_LEFT_CORNER     = C.GdkCursorType(C.GDK_TOP_LEFT_CORNER)
	TOP_RIGHT_CORNER    = C.GdkCursorType(C.GDK_TOP_RIGHT_CORNER)
	TOP_SIDE            = C.GdkCursorType(C.GDK_TOP_SIDE)
	TOP_TEE             = C.GdkCursorType(C.GDK_TOP_TEE)
	TREK                = C.GdkCursorType(C.GDK_TREK)
	UL_ANGLE            = C.GdkCursorType(C.GDK_UL_ANGLE)
	UMBRELLA            = C.GdkCursorType(C.GDK_UMBRELLA)
	UR_ANGLE            = C.GdkCursorType(C.GDK_UR_ANGLE)
	WATCH               = C.GdkCursorType(C.GDK_WATCH)
	XTERM               = C.GdkCursorType(C.GDK_XTERM)
	LAST_CURSOR         = C.GdkCursorType(C.GDK_LAST_CURSOR)
	BLANK_CURSOR        = C.GdkCursorType(C.GDK_BLANK_CURSOR)
	CURSOR_IS_PIXMAP    = C.GdkCursorType(C.GDK_CURSOR_IS_PIXMAP)

	// DeviceType
	DEVICE_TYPE_MASTER   = C.GdkDeviceType(C.GDK_DEVICE_TYPE_MASTER)
	DEVICE_TYPE_SLAVE    = C.GdkDeviceType(C.GDK_DEVICE_TYPE_SLAVE)
	DEVICE_TYPE_FLOATING = C.GdkDeviceType(C.GDK_DEVICE_TYPE_FLOATING)

	// DragProtocol
	DRAG_PROTO_NONE            = C.GdkDragProtocol(C.GDK_DRAG_PROTO_NONE)
	DRAG_PROTO_MOTIF           = C.GdkDragProtocol(C.GDK_DRAG_PROTO_MOTIF)
	DRAG_PROTO_XDND            = C.GdkDragProtocol(C.GDK_DRAG_PROTO_XDND)
	DRAG_PROTO_ROOTWIN         = C.GdkDragProtocol(C.GDK_DRAG_PROTO_ROOTWIN)
	DRAG_PROTO_WIN32_DROPFILES = C.GdkDragProtocol(C.GDK_DRAG_PROTO_WIN32_DROPFILES)
	DRAG_PROTO_OLE2            = C.GdkDragProtocol(C.GDK_DRAG_PROTO_OLE2)
	DRAG_PROTO_LOCAL           = C.GdkDragProtocol(C.GDK_DRAG_PROTO_LOCAL)

	// EventType
	NOTHING             = C.GdkEventType(C.GDK_NOTHING)
	DELETE              = C.GdkEventType(C.GDK_DELETE)
	DESTROY             = C.GdkEventType(C.GDK_DESTROY)
	EXPOSE              = C.GdkEventType(C.GDK_EXPOSE)
	MOTION_NOTIFY       = C.GdkEventType(C.GDK_MOTION_NOTIFY)
	BUTTON_PRESS        = C.GdkEventType(C.GDK_BUTTON_PRESS)
	GDK_2BUTTON_PRESS   = C.GdkEventType(C.GDK_2BUTTON_PRESS)
	DOUBLE_BUTTON_PRESS = C.GdkEventType(C.GDK_DOUBLE_BUTTON_PRESS)
	GDK_3BUTTON_PRESS   = C.GdkEventType(C.GDK_3BUTTON_PRESS)
	TRIPLE_BUTTON_PRESS = C.GdkEventType(C.GDK_TRIPLE_BUTTON_PRESS)
	BUTTON_RELEASE      = C.GdkEventType(C.GDK_BUTTON_RELEASE)
	KEY_PRESS           = C.GdkEventType(C.GDK_KEY_PRESS)
	KEY_RELEASE         = C.GdkEventType(C.GDK_KEY_RELEASE)
	ENTER_NOTIFY        = C.GdkEventType(C.GDK_ENTER_NOTIFY)
	LEAVE_NOTIFY        = C.GdkEventType(C.GDK_LEAVE_NOTIFY)
	FOCUS_CHANGE        = C.GdkEventType(C.GDK_FOCUS_CHANGE)
	CONFIGURE           = C.GdkEventType(C.GDK_CONFIGURE)
	MAP                 = C.GdkEventType(C.GDK_MAP)
	UNMAP               = C.GdkEventType(C.GDK_UNMAP)
	PROPERTY_NOTIFY     = C.GdkEventType(C.GDK_PROPERTY_NOTIFY)
	SELECTION_CLEAR     = C.GdkEventType(C.GDK_SELECTION_CLEAR)
	SELECTION_REQUEST   = C.GdkEventType(C.GDK_SELECTION_REQUEST)
	SELECTION_NOTIFY    = C.GdkEventType(C.GDK_SELECTION_NOTIFY)
	PROXIMITY_IN        = C.GdkEventType(C.GDK_PROXIMITY_IN)
	PROXIMITY_OUT       = C.GdkEventType(C.GDK_PROXIMITY_OUT)
	DRAG_ENTER          = C.GdkEventType(C.GDK_DRAG_ENTER)
	DRAG_LEAVE          = C.GdkEventType(C.GDK_DRAG_LEAVE)
	DRAG_MOTION         = C.GdkEventType(C.GDK_DRAG_MOTION)
	DRAG_STATUS         = C.GdkEventType(C.GDK_DRAG_STATUS)
	DROP_START          = C.GdkEventType(C.GDK_DROP_START)
	DROP_FINISHED       = C.GdkEventType(C.GDK_DROP_FINISHED)
	CLIENT_EVENT        = C.GdkEventType(C.GDK_CLIENT_EVENT)
	VISIBILITY_NOTIFY   = C.GdkEventType(C.GDK_VISIBILITY_NOTIFY)
	SCROLL              = C.GdkEventType(C.GDK_SCROLL)
	WINDOW_STATE        = C.GdkEventType(C.GDK_WINDOW_STATE)
	SETTING             = C.GdkEventType(C.GDK_SETTING)
	OWNER_CHANGE        = C.GdkEventType(C.GDK_OWNER_CHANGE)
	GRAB_BROKEN         = C.GdkEventType(C.GDK_GRAB_BROKEN)
	DAMAGE              = C.GdkEventType(C.GDK_DAMAGE)
	TOUCH_BEGIN         = C.GdkEventType(C.GDK_TOUCH_BEGIN)
	TOUCH_UPDATE        = C.GdkEventType(C.GDK_TOUCH_UPDATE)
	TOUCH_END           = C.GdkEventType(C.GDK_TOUCH_END)
	TOUCH_CANCEL        = C.GdkEventType(C.GDK_TOUCH_CANCEL)
	EVENT_LAST          = C.GdkEventType(C.GDK_EVENT_LAST)

	// FilterReturn
	FILTER_CONTINUE  = C.GdkFilterReturn(C.GDK_FILTER_CONTINUE)
	FILTER_TRANSLATE = C.GdkFilterReturn(C.GDK_FILTER_TRANSLATE)
	FILTER_REMOVE    = C.GdkFilterReturn(C.GDK_FILTER_REMOVE)

	// FullscreenMode
	FULLSCREEN_ON_CURRENT_MONITOR = C.GdkFullscreenMode(C.GDK_FULLSCREEN_ON_CURRENT_MONITOR)
	FULLSCREEN_ON_ALL_MONITORS    = C.GdkFullscreenMode(C.GDK_FULLSCREEN_ON_ALL_MONITORS)

	// GrabOwnership
	OWNERSHIP_NONE        = C.GdkGrabOwnership(C.GDK_OWNERSHIP_NONE)
	OWNERSHIP_WINDOW      = C.GdkGrabOwnership(C.GDK_OWNERSHIP_WINDOW)
	OWNERSHIP_APPLICATION = C.GdkGrabOwnership(C.GDK_OWNERSHIP_APPLICATION)

	// GrabStatus
	GRAB_SUCCESS         = C.GdkGrabStatus(C.GDK_GRAB_SUCCESS)
	GRAB_ALREADY_GRABBED = C.GdkGrabStatus(C.GDK_GRAB_ALREADY_GRABBED)
	GRAB_INVALID_TIME    = C.GdkGrabStatus(C.GDK_GRAB_INVALID_TIME)
	GRAB_NOT_VIEWABLE    = C.GdkGrabStatus(C.GDK_GRAB_NOT_VIEWABLE)
	GRAB_FROZEN          = C.GdkGrabStatus(C.GDK_GRAB_FROZEN)

	// Gravity
	GRAVITY_NORTH_WEST = C.GdkGravity(C.GDK_GRAVITY_NORTH_WEST)
	GRAVITY_NORTH      = C.GdkGravity(C.GDK_GRAVITY_NORTH)
	GRAVITY_NORTH_EAST = C.GdkGravity(C.GDK_GRAVITY_NORTH_EAST)
	GRAVITY_WEST       = C.GdkGravity(C.GDK_GRAVITY_WEST)
	GRAVITY_CENTER     = C.GdkGravity(C.GDK_GRAVITY_CENTER)
	GRAVITY_EAST       = C.GdkGravity(C.GDK_GRAVITY_EAST)
	GRAVITY_SOUTH_WEST = C.GdkGravity(C.GDK_GRAVITY_SOUTH_WEST)
	GRAVITY_SOUTH      = C.GdkGravity(C.GDK_GRAVITY_SOUTH)
	GRAVITY_SOUTH_EAST = C.GdkGravity(C.GDK_GRAVITY_SOUTH_EAST)
	GRAVITY_STATIC     = C.GdkGravity(C.GDK_GRAVITY_STATIC)

	// InputMode
	MODE_DISABLED = C.GdkInputMode(C.GDK_MODE_DISABLED)
	MODE_SCREEN   = C.GdkInputMode(C.GDK_MODE_SCREEN)
	MODE_WINDOW   = C.GdkInputMode(C.GDK_MODE_WINDOW)

	// InputSource
	SOURCE_MOUSE       = C.GdkInputSource(C.GDK_SOURCE_MOUSE)
	SOURCE_PEN         = C.GdkInputSource(C.GDK_SOURCE_PEN)
	SOURCE_ERASER      = C.GdkInputSource(C.GDK_SOURCE_ERASER)
	SOURCE_CURSOR      = C.GdkInputSource(C.GDK_SOURCE_CURSOR)
	SOURCE_KEYBOARD    = C.GdkInputSource(C.GDK_SOURCE_KEYBOARD)
	SOURCE_TOUCHSCREEN = C.GdkInputSource(C.GDK_SOURCE_TOUCHSCREEN)
	SOURCE_TOUCHPAD    = C.GdkInputSource(C.GDK_SOURCE_TOUCHPAD)

	// ModifierIntent
	MODIFIER_INTENT_PRIMARY_ACCELERATOR = C.GdkModifierIntent(C.GDK_MODIFIER_INTENT_PRIMARY_ACCELERATOR)
	MODIFIER_INTENT_CONTEXT_MENU        = C.GdkModifierIntent(C.GDK_MODIFIER_INTENT_CONTEXT_MENU)
	MODIFIER_INTENT_EXTEND_SELECTION    = C.GdkModifierIntent(C.GDK_MODIFIER_INTENT_EXTEND_SELECTION)
	MODIFIER_INTENT_MODIFY_SELECTION    = C.GdkModifierIntent(C.GDK_MODIFIER_INTENT_MODIFY_SELECTION)
	MODIFIER_INTENT_NO_TEXT_INPUT       = C.GdkModifierIntent(C.GDK_MODIFIER_INTENT_NO_TEXT_INPUT)
	MODIFIER_INTENT_SHIFT_GROUP         = C.GdkModifierIntent(C.GDK_MODIFIER_INTENT_SHIFT_GROUP)

	// NotifyType
	NOTIFY_ANCESTOR          = C.GdkNotifyType(C.GDK_NOTIFY_ANCESTOR)
	NOTIFY_VIRTUAL           = C.GdkNotifyType(C.GDK_NOTIFY_VIRTUAL)
	NOTIFY_INFERIOR          = C.GdkNotifyType(C.GDK_NOTIFY_INFERIOR)
	NOTIFY_NONLINEAR         = C.GdkNotifyType(C.GDK_NOTIFY_NONLINEAR)
	NOTIFY_NONLINEAR_VIRTUAL = C.GdkNotifyType(C.GDK_NOTIFY_NONLINEAR_VIRTUAL)
	NOTIFY_UNKNOWN           = C.GdkNotifyType(C.GDK_NOTIFY_UNKNOWN)

	// OwnerChange
	OWNER_CHANGE_NEW_OWNER = C.GdkOwnerChange(C.GDK_OWNER_CHANGE_NEW_OWNER)
	OWNER_CHANGE_DESTROY   = C.GdkOwnerChange(C.GDK_OWNER_CHANGE_DESTROY)
	OWNER_CHANGE_CLOSE     = C.GdkOwnerChange(C.GDK_OWNER_CHANGE_CLOSE)

	// PropMode
	PROP_MODE_REPLACE = C.GdkPropMode(C.GDK_PROP_MODE_REPLACE)
	PROP_MODE_PREPEND = C.GdkPropMode(C.GDK_PROP_MODE_PREPEND)
	PROP_MODE_APPEND  = C.GdkPropMode(C.GDK_PROP_MODE_APPEND)

	// PropertyState
	PROPERTY_NEW_VALUE = C.GdkPropertyState(C.GDK_PROPERTY_NEW_VALUE)
	PROPERTY_DELETE    = C.GdkPropertyState(C.GDK_PROPERTY_DELETE)

	// ScrollDirection
	SCROLL_UP     = C.GdkScrollDirection(C.GDK_SCROLL_UP)
	SCROLL_DOWN   = C.GdkScrollDirection(C.GDK_SCROLL_DOWN)
	SCROLL_LEFT   = C.GdkScrollDirection(C.GDK_SCROLL_LEFT)
	SCROLL_RIGHT  = C.GdkScrollDirection(C.GDK_SCROLL_RIGHT)
	SCROLL_SMOOTH = C.GdkScrollDirection(C.GDK_SCROLL_SMOOTH)

	// SettingAction
	SETTING_ACTION_NEW     = C.GdkSettingAction(C.GDK_SETTING_ACTION_NEW)
	SETTING_ACTION_CHANGED = C.GdkSettingAction(C.GDK_SETTING_ACTION_CHANGED)
	SETTING_ACTION_DELETED = C.GdkSettingAction(C.GDK_SETTING_ACTION_DELETED)

	// Status
	OK          = C.GdkStatus(C.GDK_OK)
	ERROR       = C.GdkStatus(C.GDK_ERROR)
	ERROR_PARAM = C.GdkStatus(C.GDK_ERROR_PARAM)
	ERROR_FILE  = C.GdkStatus(C.GDK_ERROR_FILE)
	ERROR_MEM   = C.GdkStatus(C.GDK_ERROR_MEM)

	// VisibilityState
	VISIBILITY_UNOBSCURED     = C.GdkVisibilityState(C.GDK_VISIBILITY_UNOBSCURED)
	VISIBILITY_PARTIAL        = C.GdkVisibilityState(C.GDK_VISIBILITY_PARTIAL)
	VISIBILITY_FULLY_OBSCURED = C.GdkVisibilityState(C.GDK_VISIBILITY_FULLY_OBSCURED)

	// VisualType
	VISUAL_STATIC_GRAY  = C.GdkVisualType(C.GDK_VISUAL_STATIC_GRAY)
	VISUAL_GRAYSCALE    = C.GdkVisualType(C.GDK_VISUAL_GRAYSCALE)
	VISUAL_STATIC_COLOR = C.GdkVisualType(C.GDK_VISUAL_STATIC_COLOR)
	VISUAL_PSEUDO_COLOR = C.GdkVisualType(C.GDK_VISUAL_PSEUDO_COLOR)
	VISUAL_TRUE_COLOR   = C.GdkVisualType(C.GDK_VISUAL_TRUE_COLOR)
	VISUAL_DIRECT_COLOR = C.GdkVisualType(C.GDK_VISUAL_DIRECT_COLOR)

	// WindowEdge
	WINDOW_EDGE_NORTH_WEST = C.GdkWindowEdge(C.GDK_WINDOW_EDGE_NORTH_WEST)
	WINDOW_EDGE_NORTH      = C.GdkWindowEdge(C.GDK_WINDOW_EDGE_NORTH)
	WINDOW_EDGE_NORTH_EAST = C.GdkWindowEdge(C.GDK_WINDOW_EDGE_NORTH_EAST)
	WINDOW_EDGE_WEST       = C.GdkWindowEdge(C.GDK_WINDOW_EDGE_WEST)
	WINDOW_EDGE_EAST       = C.GdkWindowEdge(C.GDK_WINDOW_EDGE_EAST)
	WINDOW_EDGE_SOUTH_WEST = C.GdkWindowEdge(C.GDK_WINDOW_EDGE_SOUTH_WEST)
	WINDOW_EDGE_SOUTH      = C.GdkWindowEdge(C.GDK_WINDOW_EDGE_SOUTH)
	WINDOW_EDGE_SOUTH_EAST = C.GdkWindowEdge(C.GDK_WINDOW_EDGE_SOUTH_EAST)

	// WindowType
	WINDOW_ROOT      = C.GdkWindowType(C.GDK_WINDOW_ROOT)
	WINDOW_TOPLEVEL  = C.GdkWindowType(C.GDK_WINDOW_TOPLEVEL)
	WINDOW_CHILD     = C.GdkWindowType(C.GDK_WINDOW_CHILD)
	WINDOW_TEMP      = C.GdkWindowType(C.GDK_WINDOW_TEMP)
	WINDOW_FOREIGN   = C.GdkWindowType(C.GDK_WINDOW_FOREIGN)
	WINDOW_OFFSCREEN = C.GdkWindowType(C.GDK_WINDOW_OFFSCREEN)

	// WindowTypeHint
	WINDOW_TYPE_HINT_NORMAL        = C.GdkWindowTypeHint(C.GDK_WINDOW_TYPE_HINT_NORMAL)
	WINDOW_TYPE_HINT_DIALOG        = C.GdkWindowTypeHint(C.GDK_WINDOW_TYPE_HINT_DIALOG)
	WINDOW_TYPE_HINT_MENU          = C.GdkWindowTypeHint(C.GDK_WINDOW_TYPE_HINT_MENU)
	WINDOW_TYPE_HINT_TOOLBAR       = C.GdkWindowTypeHint(C.GDK_WINDOW_TYPE_HINT_TOOLBAR)
	WINDOW_TYPE_HINT_SPLASHSCREEN  = C.GdkWindowTypeHint(C.GDK_WINDOW_TYPE_HINT_SPLASHSCREEN)
	WINDOW_TYPE_HINT_UTILITY       = C.GdkWindowTypeHint(C.GDK_WINDOW_TYPE_HINT_UTILITY)
	WINDOW_TYPE_HINT_DOCK          = C.GdkWindowTypeHint(C.GDK_WINDOW_TYPE_HINT_DOCK)
	WINDOW_TYPE_HINT_DESKTOP       = C.GdkWindowTypeHint(C.GDK_WINDOW_TYPE_HINT_DESKTOP)
	WINDOW_TYPE_HINT_DROPDOWN_MENU = C.GdkWindowTypeHint(C.GDK_WINDOW_TYPE_HINT_DROPDOWN_MENU)
	WINDOW_TYPE_HINT_POPUP_MENU    = C.GdkWindowTypeHint(C.GDK_WINDOW_TYPE_HINT_POPUP_MENU)
	WINDOW_TYPE_HINT_TOOLTIP       = C.GdkWindowTypeHint(C.GDK_WINDOW_TYPE_HINT_TOOLTIP)
	WINDOW_TYPE_HINT_NOTIFICATION  = C.GdkWindowTypeHint(C.GDK_WINDOW_TYPE_HINT_NOTIFICATION)
	WINDOW_TYPE_HINT_COMBO         = C.GdkWindowTypeHint(C.GDK_WINDOW_TYPE_HINT_COMBO)
	WINDOW_TYPE_HINT_DND           = C.GdkWindowTypeHint(C.GDK_WINDOW_TYPE_HINT_DND)

	// WindowWindowClass
	INPUT_OUTPUT = C.GdkWindowWindowClass(C.GDK_INPUT_OUTPUT)
	INPUT_ONLY   = C.GdkWindowWindowClass(C.GDK_INPUT_ONLY)
)
