package gdkpixbuf

/*
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gdk-pixbuf/gdk-pixdata.h>
#include <stdlib.h>

gint __GDK_PIXBUF_FEATURES_H = GDK_PIXBUF_FEATURES_H;
gint __GDK_PIXBUF_MAGIC_NUMBER = GDK_PIXBUF_MAGIC_NUMBER;
gint __GDK_PIXBUF_MAJOR = GDK_PIXBUF_MAJOR;
gint __GDK_PIXBUF_MICRO = GDK_PIXBUF_MICRO;
gint __GDK_PIXBUF_MINOR = GDK_PIXBUF_MINOR;
gchar* __GDK_PIXBUF_VERSION = GDK_PIXBUF_VERSION;
gint __GDK_PIXDATA_HEADER_LENGTH = GDK_PIXDATA_HEADER_LENGTH;
*/
import "C"

var (
	PIXBUF_FEATURES_H     = C.__GDK_PIXBUF_FEATURES_H
	PIXBUF_MAGIC_NUMBER   = C.__GDK_PIXBUF_MAGIC_NUMBER
	PIXBUF_MAJOR          = C.__GDK_PIXBUF_MAJOR
	PIXBUF_MICRO          = C.__GDK_PIXBUF_MICRO
	PIXBUF_MINOR          = C.__GDK_PIXBUF_MINOR
	PIXBUF_VERSION        = C.__GDK_PIXBUF_VERSION
	PIXDATA_HEADER_LENGTH = C.__GDK_PIXDATA_HEADER_LENGTH
)
