package gtk

/*
#include <gtk/gtk.h>
#include <gtk/gtkx.h>
#include <stdlib.h>
*/
import "C"

var (
	// AccelFlags
	ACCEL_VISIBLE = C.GTK_ACCEL_VISIBLE
	ACCEL_LOCKED  = C.GTK_ACCEL_LOCKED
	ACCEL_MASK    = C.GTK_ACCEL_MASK

	// ApplicationInhibitFlags
	APPLICATION_INHIBIT_LOGOUT  = C.GTK_APPLICATION_INHIBIT_LOGOUT
	APPLICATION_INHIBIT_SWITCH  = C.GTK_APPLICATION_INHIBIT_SWITCH
	APPLICATION_INHIBIT_SUSPEND = C.GTK_APPLICATION_INHIBIT_SUSPEND
	APPLICATION_INHIBIT_IDLE    = C.GTK_APPLICATION_INHIBIT_IDLE

	// AttachOptions
	EXPAND = C.GTK_EXPAND
	SHRINK = C.GTK_SHRINK
	FILL   = C.GTK_FILL

	// CalendarDisplayOptions
	CALENDAR_SHOW_HEADING      = C.GTK_CALENDAR_SHOW_HEADING
	CALENDAR_SHOW_DAY_NAMES    = C.GTK_CALENDAR_SHOW_DAY_NAMES
	CALENDAR_NO_MONTH_CHANGE   = C.GTK_CALENDAR_NO_MONTH_CHANGE
	CALENDAR_SHOW_WEEK_NUMBERS = C.GTK_CALENDAR_SHOW_WEEK_NUMBERS
	CALENDAR_SHOW_DETAILS      = C.GTK_CALENDAR_SHOW_DETAILS

	// CellRendererState
	CELL_RENDERER_SELECTED    = C.GTK_CELL_RENDERER_SELECTED
	CELL_RENDERER_PRELIT      = C.GTK_CELL_RENDERER_PRELIT
	CELL_RENDERER_INSENSITIVE = C.GTK_CELL_RENDERER_INSENSITIVE
	CELL_RENDERER_SORTED      = C.GTK_CELL_RENDERER_SORTED
	CELL_RENDERER_FOCUSED     = C.GTK_CELL_RENDERER_FOCUSED
	CELL_RENDERER_EXPANDABLE  = C.GTK_CELL_RENDERER_EXPANDABLE
	CELL_RENDERER_EXPANDED    = C.GTK_CELL_RENDERER_EXPANDED

	// DebugFlag
	DEBUG_MISC           = C.GTK_DEBUG_MISC
	DEBUG_PLUGSOCKET     = C.GTK_DEBUG_PLUGSOCKET
	DEBUG_TEXT           = C.GTK_DEBUG_TEXT
	DEBUG_TREE           = C.GTK_DEBUG_TREE
	DEBUG_UPDATES        = C.GTK_DEBUG_UPDATES
	DEBUG_KEYBINDINGS    = C.GTK_DEBUG_KEYBINDINGS
	DEBUG_MULTIHEAD      = C.GTK_DEBUG_MULTIHEAD
	DEBUG_MODULES        = C.GTK_DEBUG_MODULES
	DEBUG_GEOMETRY       = C.GTK_DEBUG_GEOMETRY
	DEBUG_ICONTHEME      = C.GTK_DEBUG_ICONTHEME
	DEBUG_PRINTING       = C.GTK_DEBUG_PRINTING
	DEBUG_BUILDER        = C.GTK_DEBUG_BUILDER
	DEBUG_SIZE_REQUEST   = C.GTK_DEBUG_SIZE_REQUEST
	DEBUG_NO_CSS_CACHE   = C.GTK_DEBUG_NO_CSS_CACHE
	DEBUG_BASELINES      = C.GTK_DEBUG_BASELINES
	DEBUG_PIXEL_CACHE    = C.GTK_DEBUG_PIXEL_CACHE
	DEBUG_NO_PIXEL_CACHE = C.GTK_DEBUG_NO_PIXEL_CACHE

	// DestDefaults
	DEST_DEFAULT_MOTION    = C.GTK_DEST_DEFAULT_MOTION
	DEST_DEFAULT_HIGHLIGHT = C.GTK_DEST_DEFAULT_HIGHLIGHT
	DEST_DEFAULT_DROP      = C.GTK_DEST_DEFAULT_DROP
	DEST_DEFAULT_ALL       = C.GTK_DEST_DEFAULT_ALL

	// DialogFlags
	DIALOG_MODAL               = C.GTK_DIALOG_MODAL
	DIALOG_DESTROY_WITH_PARENT = C.GTK_DIALOG_DESTROY_WITH_PARENT
	DIALOG_USE_HEADER_BAR      = C.GTK_DIALOG_USE_HEADER_BAR

	// FileFilterFlags
	FILE_FILTER_FILENAME     = C.GTK_FILE_FILTER_FILENAME
	FILE_FILTER_URI          = C.GTK_FILE_FILTER_URI
	FILE_FILTER_DISPLAY_NAME = C.GTK_FILE_FILTER_DISPLAY_NAME
	FILE_FILTER_MIME_TYPE    = C.GTK_FILE_FILTER_MIME_TYPE

	// IconLookupFlags
	ICON_LOOKUP_NO_SVG           = C.GTK_ICON_LOOKUP_NO_SVG
	ICON_LOOKUP_FORCE_SVG        = C.GTK_ICON_LOOKUP_FORCE_SVG
	ICON_LOOKUP_USE_BUILTIN      = C.GTK_ICON_LOOKUP_USE_BUILTIN
	ICON_LOOKUP_GENERIC_FALLBACK = C.GTK_ICON_LOOKUP_GENERIC_FALLBACK
	ICON_LOOKUP_FORCE_SIZE       = C.GTK_ICON_LOOKUP_FORCE_SIZE

	// InputHints
	INPUT_HINT_NONE                = C.GTK_INPUT_HINT_NONE
	INPUT_HINT_SPELLCHECK          = C.GTK_INPUT_HINT_SPELLCHECK
	INPUT_HINT_NO_SPELLCHECK       = C.GTK_INPUT_HINT_NO_SPELLCHECK
	INPUT_HINT_WORD_COMPLETION     = C.GTK_INPUT_HINT_WORD_COMPLETION
	INPUT_HINT_LOWERCASE           = C.GTK_INPUT_HINT_LOWERCASE
	INPUT_HINT_UPPERCASE_CHARS     = C.GTK_INPUT_HINT_UPPERCASE_CHARS
	INPUT_HINT_UPPERCASE_WORDS     = C.GTK_INPUT_HINT_UPPERCASE_WORDS
	INPUT_HINT_UPPERCASE_SENTENCES = C.GTK_INPUT_HINT_UPPERCASE_SENTENCES
	INPUT_HINT_INHIBIT_OSK         = C.GTK_INPUT_HINT_INHIBIT_OSK

	// JunctionSides
	JUNCTION_NONE               = C.GTK_JUNCTION_NONE
	JUNCTION_CORNER_TOPLEFT     = C.GTK_JUNCTION_CORNER_TOPLEFT
	JUNCTION_CORNER_TOPRIGHT    = C.GTK_JUNCTION_CORNER_TOPRIGHT
	JUNCTION_CORNER_BOTTOMLEFT  = C.GTK_JUNCTION_CORNER_BOTTOMLEFT
	JUNCTION_CORNER_BOTTOMRIGHT = C.GTK_JUNCTION_CORNER_BOTTOMRIGHT
	JUNCTION_TOP                = C.GTK_JUNCTION_TOP
	JUNCTION_BOTTOM             = C.GTK_JUNCTION_BOTTOM
	JUNCTION_LEFT               = C.GTK_JUNCTION_LEFT
	JUNCTION_RIGHT              = C.GTK_JUNCTION_RIGHT

	// PlacesOpenFlags
	PLACES_OPEN_NORMAL     = C.GTK_PLACES_OPEN_NORMAL
	PLACES_OPEN_NEW_TAB    = C.GTK_PLACES_OPEN_NEW_TAB
	PLACES_OPEN_NEW_WINDOW = C.GTK_PLACES_OPEN_NEW_WINDOW

	// RcFlags
	RC_FG   = C.GTK_RC_FG
	RC_BG   = C.GTK_RC_BG
	RC_TEXT = C.GTK_RC_TEXT
	RC_BASE = C.GTK_RC_BASE

	// RecentFilterFlags
	RECENT_FILTER_URI          = C.GTK_RECENT_FILTER_URI
	RECENT_FILTER_DISPLAY_NAME = C.GTK_RECENT_FILTER_DISPLAY_NAME
	RECENT_FILTER_MIME_TYPE    = C.GTK_RECENT_FILTER_MIME_TYPE
	RECENT_FILTER_APPLICATION  = C.GTK_RECENT_FILTER_APPLICATION
	RECENT_FILTER_GROUP        = C.GTK_RECENT_FILTER_GROUP
	RECENT_FILTER_AGE          = C.GTK_RECENT_FILTER_AGE

	// RegionFlags
	REGION_EVEN   = C.GTK_REGION_EVEN
	REGION_ODD    = C.GTK_REGION_ODD
	REGION_FIRST  = C.GTK_REGION_FIRST
	REGION_LAST   = C.GTK_REGION_LAST
	REGION_ONLY   = C.GTK_REGION_ONLY
	REGION_SORTED = C.GTK_REGION_SORTED

	// StateFlags
	STATE_FLAG_NORMAL       = C.GTK_STATE_FLAG_NORMAL
	STATE_FLAG_ACTIVE       = C.GTK_STATE_FLAG_ACTIVE
	STATE_FLAG_PRELIGHT     = C.GTK_STATE_FLAG_PRELIGHT
	STATE_FLAG_SELECTED     = C.GTK_STATE_FLAG_SELECTED
	STATE_FLAG_INSENSITIVE  = C.GTK_STATE_FLAG_INSENSITIVE
	STATE_FLAG_INCONSISTENT = C.GTK_STATE_FLAG_INCONSISTENT
	STATE_FLAG_FOCUSED      = C.GTK_STATE_FLAG_FOCUSED
	STATE_FLAG_BACKDROP     = C.GTK_STATE_FLAG_BACKDROP
	STATE_FLAG_DIR_LTR      = C.GTK_STATE_FLAG_DIR_LTR
	STATE_FLAG_DIR_RTL      = C.GTK_STATE_FLAG_DIR_RTL
	STATE_FLAG_LINK         = C.GTK_STATE_FLAG_LINK
	STATE_FLAG_VISITED      = C.GTK_STATE_FLAG_VISITED

	// TargetFlags
	TARGET_SAME_APP     = C.GTK_TARGET_SAME_APP
	TARGET_SAME_WIDGET  = C.GTK_TARGET_SAME_WIDGET
	TARGET_OTHER_APP    = C.GTK_TARGET_OTHER_APP
	TARGET_OTHER_WIDGET = C.GTK_TARGET_OTHER_WIDGET

	// TextSearchFlags
	TEXT_SEARCH_VISIBLE_ONLY     = C.GTK_TEXT_SEARCH_VISIBLE_ONLY
	TEXT_SEARCH_TEXT_ONLY        = C.GTK_TEXT_SEARCH_TEXT_ONLY
	TEXT_SEARCH_CASE_INSENSITIVE = C.GTK_TEXT_SEARCH_CASE_INSENSITIVE

	// ToolPaletteDragTargets
	TOOL_PALETTE_DRAG_ITEMS  = C.GTK_TOOL_PALETTE_DRAG_ITEMS
	TOOL_PALETTE_DRAG_GROUPS = C.GTK_TOOL_PALETTE_DRAG_GROUPS

	// TreeModelFlags
	TREE_MODEL_ITERS_PERSIST = C.GTK_TREE_MODEL_ITERS_PERSIST
	TREE_MODEL_LIST_ONLY     = C.GTK_TREE_MODEL_LIST_ONLY

	// UIManagerItemType
	UI_MANAGER_AUTO              = C.GTK_UI_MANAGER_AUTO
	UI_MANAGER_MENUBAR           = C.GTK_UI_MANAGER_MENUBAR
	UI_MANAGER_MENU              = C.GTK_UI_MANAGER_MENU
	UI_MANAGER_TOOLBAR           = C.GTK_UI_MANAGER_TOOLBAR
	UI_MANAGER_PLACEHOLDER       = C.GTK_UI_MANAGER_PLACEHOLDER
	UI_MANAGER_POPUP             = C.GTK_UI_MANAGER_POPUP
	UI_MANAGER_MENUITEM          = C.GTK_UI_MANAGER_MENUITEM
	UI_MANAGER_TOOLITEM          = C.GTK_UI_MANAGER_TOOLITEM
	UI_MANAGER_SEPARATOR         = C.GTK_UI_MANAGER_SEPARATOR
	UI_MANAGER_ACCELERATOR       = C.GTK_UI_MANAGER_ACCELERATOR
	UI_MANAGER_POPUP_WITH_ACCELS = C.GTK_UI_MANAGER_POPUP_WITH_ACCELS
)
