package gtk

/*
#include <gtk/gtk.h>
#include <stdlib.h>

gint __GTK_BINARY_AGE = GTK_BINARY_AGE;
gint __GTK_INPUT_ERROR = GTK_INPUT_ERROR;
gint __GTK_INTERFACE_AGE = GTK_INTERFACE_AGE;
gchar* __GTK_LEVEL_BAR_OFFSET_HIGH = GTK_LEVEL_BAR_OFFSET_HIGH;
gchar* __GTK_LEVEL_BAR_OFFSET_LOW = GTK_LEVEL_BAR_OFFSET_LOW;
gint __GTK_MAJOR_VERSION = GTK_MAJOR_VERSION;
gint __GTK_MAX_COMPOSE_LEN = GTK_MAX_COMPOSE_LEN;
gint __GTK_MICRO_VERSION = GTK_MICRO_VERSION;
gint __GTK_MINOR_VERSION = GTK_MINOR_VERSION;
gchar* __GTK_PAPER_NAME_A3 = GTK_PAPER_NAME_A3;
gchar* __GTK_PAPER_NAME_A4 = GTK_PAPER_NAME_A4;
gchar* __GTK_PAPER_NAME_A5 = GTK_PAPER_NAME_A5;
gchar* __GTK_PAPER_NAME_B5 = GTK_PAPER_NAME_B5;
gchar* __GTK_PAPER_NAME_EXECUTIVE = GTK_PAPER_NAME_EXECUTIVE;
gchar* __GTK_PAPER_NAME_LEGAL = GTK_PAPER_NAME_LEGAL;
gchar* __GTK_PAPER_NAME_LETTER = GTK_PAPER_NAME_LETTER;
gint __GTK_PATH_PRIO_MASK = GTK_PATH_PRIO_MASK;
gchar* __GTK_PRINT_SETTINGS_COLLATE = GTK_PRINT_SETTINGS_COLLATE;
gchar* __GTK_PRINT_SETTINGS_DEFAULT_SOURCE = GTK_PRINT_SETTINGS_DEFAULT_SOURCE;
gchar* __GTK_PRINT_SETTINGS_DITHER = GTK_PRINT_SETTINGS_DITHER;
gchar* __GTK_PRINT_SETTINGS_DUPLEX = GTK_PRINT_SETTINGS_DUPLEX;
gchar* __GTK_PRINT_SETTINGS_FINISHINGS = GTK_PRINT_SETTINGS_FINISHINGS;
gchar* __GTK_PRINT_SETTINGS_MEDIA_TYPE = GTK_PRINT_SETTINGS_MEDIA_TYPE;
gchar* __GTK_PRINT_SETTINGS_NUMBER_UP = GTK_PRINT_SETTINGS_NUMBER_UP;
gchar* __GTK_PRINT_SETTINGS_NUMBER_UP_LAYOUT = GTK_PRINT_SETTINGS_NUMBER_UP_LAYOUT;
gchar* __GTK_PRINT_SETTINGS_N_COPIES = GTK_PRINT_SETTINGS_N_COPIES;
gchar* __GTK_PRINT_SETTINGS_ORIENTATION = GTK_PRINT_SETTINGS_ORIENTATION;
gchar* __GTK_PRINT_SETTINGS_OUTPUT_BASENAME = GTK_PRINT_SETTINGS_OUTPUT_BASENAME;
gchar* __GTK_PRINT_SETTINGS_OUTPUT_BIN = GTK_PRINT_SETTINGS_OUTPUT_BIN;
gchar* __GTK_PRINT_SETTINGS_OUTPUT_DIR = GTK_PRINT_SETTINGS_OUTPUT_DIR;
gchar* __GTK_PRINT_SETTINGS_OUTPUT_FILE_FORMAT = GTK_PRINT_SETTINGS_OUTPUT_FILE_FORMAT;
gchar* __GTK_PRINT_SETTINGS_OUTPUT_URI = GTK_PRINT_SETTINGS_OUTPUT_URI;
gchar* __GTK_PRINT_SETTINGS_PAGE_RANGES = GTK_PRINT_SETTINGS_PAGE_RANGES;
gchar* __GTK_PRINT_SETTINGS_PAGE_SET = GTK_PRINT_SETTINGS_PAGE_SET;
gchar* __GTK_PRINT_SETTINGS_PAPER_FORMAT = GTK_PRINT_SETTINGS_PAPER_FORMAT;
gchar* __GTK_PRINT_SETTINGS_PAPER_HEIGHT = GTK_PRINT_SETTINGS_PAPER_HEIGHT;
gchar* __GTK_PRINT_SETTINGS_PAPER_WIDTH = GTK_PRINT_SETTINGS_PAPER_WIDTH;
gchar* __GTK_PRINT_SETTINGS_PRINTER = GTK_PRINT_SETTINGS_PRINTER;
gchar* __GTK_PRINT_SETTINGS_PRINTER_LPI = GTK_PRINT_SETTINGS_PRINTER_LPI;
gchar* __GTK_PRINT_SETTINGS_PRINT_PAGES = GTK_PRINT_SETTINGS_PRINT_PAGES;
gchar* __GTK_PRINT_SETTINGS_QUALITY = GTK_PRINT_SETTINGS_QUALITY;
gchar* __GTK_PRINT_SETTINGS_RESOLUTION = GTK_PRINT_SETTINGS_RESOLUTION;
gchar* __GTK_PRINT_SETTINGS_RESOLUTION_X = GTK_PRINT_SETTINGS_RESOLUTION_X;
gchar* __GTK_PRINT_SETTINGS_RESOLUTION_Y = GTK_PRINT_SETTINGS_RESOLUTION_Y;
gchar* __GTK_PRINT_SETTINGS_REVERSE = GTK_PRINT_SETTINGS_REVERSE;
gchar* __GTK_PRINT_SETTINGS_SCALE = GTK_PRINT_SETTINGS_SCALE;
gchar* __GTK_PRINT_SETTINGS_USE_COLOR = GTK_PRINT_SETTINGS_USE_COLOR;
gchar* __GTK_PRINT_SETTINGS_WIN32_DRIVER_EXTRA = GTK_PRINT_SETTINGS_WIN32_DRIVER_EXTRA;
gchar* __GTK_PRINT_SETTINGS_WIN32_DRIVER_VERSION = GTK_PRINT_SETTINGS_WIN32_DRIVER_VERSION;
gint __GTK_PRIORITY_RESIZE = GTK_PRIORITY_RESIZE;
gchar* __GTK_STYLE_CLASS_ACCELERATOR = GTK_STYLE_CLASS_ACCELERATOR;
gchar* __GTK_STYLE_CLASS_ARROW = GTK_STYLE_CLASS_ARROW;
gchar* __GTK_STYLE_CLASS_BACKGROUND = GTK_STYLE_CLASS_BACKGROUND;
gchar* __GTK_STYLE_CLASS_BOTTOM = GTK_STYLE_CLASS_BOTTOM;
gchar* __GTK_STYLE_CLASS_BUTTON = GTK_STYLE_CLASS_BUTTON;
gchar* __GTK_STYLE_CLASS_CALENDAR = GTK_STYLE_CLASS_CALENDAR;
gchar* __GTK_STYLE_CLASS_CELL = GTK_STYLE_CLASS_CELL;
gchar* __GTK_STYLE_CLASS_CHECK = GTK_STYLE_CLASS_CHECK;
gchar* __GTK_STYLE_CLASS_COMBOBOX_ENTRY = GTK_STYLE_CLASS_COMBOBOX_ENTRY;
gchar* __GTK_STYLE_CLASS_CONTEXT_MENU = GTK_STYLE_CLASS_CONTEXT_MENU;
gchar* __GTK_STYLE_CLASS_CURSOR_HANDLE = GTK_STYLE_CLASS_CURSOR_HANDLE;
gchar* __GTK_STYLE_CLASS_DEFAULT = GTK_STYLE_CLASS_DEFAULT;
gchar* __GTK_STYLE_CLASS_DESTRUCTIVE_ACTION = GTK_STYLE_CLASS_DESTRUCTIVE_ACTION;
gchar* __GTK_STYLE_CLASS_DIM_LABEL = GTK_STYLE_CLASS_DIM_LABEL;
gchar* __GTK_STYLE_CLASS_DND = GTK_STYLE_CLASS_DND;
gchar* __GTK_STYLE_CLASS_DOCK = GTK_STYLE_CLASS_DOCK;
gchar* __GTK_STYLE_CLASS_ENTRY = GTK_STYLE_CLASS_ENTRY;
gchar* __GTK_STYLE_CLASS_ERROR = GTK_STYLE_CLASS_ERROR;
gchar* __GTK_STYLE_CLASS_EXPANDER = GTK_STYLE_CLASS_EXPANDER;
gchar* __GTK_STYLE_CLASS_FRAME = GTK_STYLE_CLASS_FRAME;
gchar* __GTK_STYLE_CLASS_GRIP = GTK_STYLE_CLASS_GRIP;
gchar* __GTK_STYLE_CLASS_HEADER = GTK_STYLE_CLASS_HEADER;
gchar* __GTK_STYLE_CLASS_HIGHLIGHT = GTK_STYLE_CLASS_HIGHLIGHT;
gchar* __GTK_STYLE_CLASS_HORIZONTAL = GTK_STYLE_CLASS_HORIZONTAL;
gchar* __GTK_STYLE_CLASS_IMAGE = GTK_STYLE_CLASS_IMAGE;
gchar* __GTK_STYLE_CLASS_INFO = GTK_STYLE_CLASS_INFO;
gchar* __GTK_STYLE_CLASS_INLINE_TOOLBAR = GTK_STYLE_CLASS_INLINE_TOOLBAR;
gchar* __GTK_STYLE_CLASS_INSERTION_CURSOR = GTK_STYLE_CLASS_INSERTION_CURSOR;
gchar* __GTK_STYLE_CLASS_LEFT = GTK_STYLE_CLASS_LEFT;
gchar* __GTK_STYLE_CLASS_LEVEL_BAR = GTK_STYLE_CLASS_LEVEL_BAR;
gchar* __GTK_STYLE_CLASS_LINKED = GTK_STYLE_CLASS_LINKED;
gchar* __GTK_STYLE_CLASS_LIST = GTK_STYLE_CLASS_LIST;
gchar* __GTK_STYLE_CLASS_LIST_ROW = GTK_STYLE_CLASS_LIST_ROW;
gchar* __GTK_STYLE_CLASS_MARK = GTK_STYLE_CLASS_MARK;
gchar* __GTK_STYLE_CLASS_MENU = GTK_STYLE_CLASS_MENU;
gchar* __GTK_STYLE_CLASS_MENUBAR = GTK_STYLE_CLASS_MENUBAR;
gchar* __GTK_STYLE_CLASS_MENUITEM = GTK_STYLE_CLASS_MENUITEM;
gchar* __GTK_STYLE_CLASS_NEEDS_ATTENTION = GTK_STYLE_CLASS_NEEDS_ATTENTION;
gchar* __GTK_STYLE_CLASS_NOTEBOOK = GTK_STYLE_CLASS_NOTEBOOK;
gchar* __GTK_STYLE_CLASS_OSD = GTK_STYLE_CLASS_OSD;
gchar* __GTK_STYLE_CLASS_PANE_SEPARATOR = GTK_STYLE_CLASS_PANE_SEPARATOR;
gchar* __GTK_STYLE_CLASS_PRIMARY_TOOLBAR = GTK_STYLE_CLASS_PRIMARY_TOOLBAR;
gchar* __GTK_STYLE_CLASS_PROGRESSBAR = GTK_STYLE_CLASS_PROGRESSBAR;
gchar* __GTK_STYLE_CLASS_PULSE = GTK_STYLE_CLASS_PULSE;
gchar* __GTK_STYLE_CLASS_QUESTION = GTK_STYLE_CLASS_QUESTION;
gchar* __GTK_STYLE_CLASS_RADIO = GTK_STYLE_CLASS_RADIO;
gchar* __GTK_STYLE_CLASS_RAISED = GTK_STYLE_CLASS_RAISED;
gchar* __GTK_STYLE_CLASS_READ_ONLY = GTK_STYLE_CLASS_READ_ONLY;
gchar* __GTK_STYLE_CLASS_RIGHT = GTK_STYLE_CLASS_RIGHT;
gchar* __GTK_STYLE_CLASS_RUBBERBAND = GTK_STYLE_CLASS_RUBBERBAND;
gchar* __GTK_STYLE_CLASS_SCALE = GTK_STYLE_CLASS_SCALE;
gchar* __GTK_STYLE_CLASS_SCALE_HAS_MARKS_ABOVE = GTK_STYLE_CLASS_SCALE_HAS_MARKS_ABOVE;
gchar* __GTK_STYLE_CLASS_SCALE_HAS_MARKS_BELOW = GTK_STYLE_CLASS_SCALE_HAS_MARKS_BELOW;
gchar* __GTK_STYLE_CLASS_SCROLLBAR = GTK_STYLE_CLASS_SCROLLBAR;
gchar* __GTK_STYLE_CLASS_SCROLLBARS_JUNCTION = GTK_STYLE_CLASS_SCROLLBARS_JUNCTION;
gchar* __GTK_STYLE_CLASS_SEPARATOR = GTK_STYLE_CLASS_SEPARATOR;
gchar* __GTK_STYLE_CLASS_SIDEBAR = GTK_STYLE_CLASS_SIDEBAR;
gchar* __GTK_STYLE_CLASS_SLIDER = GTK_STYLE_CLASS_SLIDER;
gchar* __GTK_STYLE_CLASS_SPINBUTTON = GTK_STYLE_CLASS_SPINBUTTON;
gchar* __GTK_STYLE_CLASS_SPINNER = GTK_STYLE_CLASS_SPINNER;
gchar* __GTK_STYLE_CLASS_SUGGESTED_ACTION = GTK_STYLE_CLASS_SUGGESTED_ACTION;
gchar* __GTK_STYLE_CLASS_TITLEBAR = GTK_STYLE_CLASS_TITLEBAR;
gchar* __GTK_STYLE_CLASS_TOOLBAR = GTK_STYLE_CLASS_TOOLBAR;
gchar* __GTK_STYLE_CLASS_TOOLTIP = GTK_STYLE_CLASS_TOOLTIP;
gchar* __GTK_STYLE_CLASS_TOP = GTK_STYLE_CLASS_TOP;
gchar* __GTK_STYLE_CLASS_TROUGH = GTK_STYLE_CLASS_TROUGH;
gchar* __GTK_STYLE_CLASS_VERTICAL = GTK_STYLE_CLASS_VERTICAL;
gchar* __GTK_STYLE_CLASS_VIEW = GTK_STYLE_CLASS_VIEW;
gchar* __GTK_STYLE_CLASS_WARNING = GTK_STYLE_CLASS_WARNING;
gchar* __GTK_STYLE_PROPERTY_BACKGROUND_COLOR = GTK_STYLE_PROPERTY_BACKGROUND_COLOR;
gchar* __GTK_STYLE_PROPERTY_BACKGROUND_IMAGE = GTK_STYLE_PROPERTY_BACKGROUND_IMAGE;
gchar* __GTK_STYLE_PROPERTY_BORDER_COLOR = GTK_STYLE_PROPERTY_BORDER_COLOR;
gchar* __GTK_STYLE_PROPERTY_BORDER_RADIUS = GTK_STYLE_PROPERTY_BORDER_RADIUS;
gchar* __GTK_STYLE_PROPERTY_BORDER_STYLE = GTK_STYLE_PROPERTY_BORDER_STYLE;
gchar* __GTK_STYLE_PROPERTY_BORDER_WIDTH = GTK_STYLE_PROPERTY_BORDER_WIDTH;
gchar* __GTK_STYLE_PROPERTY_COLOR = GTK_STYLE_PROPERTY_COLOR;
gchar* __GTK_STYLE_PROPERTY_FONT = GTK_STYLE_PROPERTY_FONT;
gchar* __GTK_STYLE_PROPERTY_MARGIN = GTK_STYLE_PROPERTY_MARGIN;
gchar* __GTK_STYLE_PROPERTY_PADDING = GTK_STYLE_PROPERTY_PADDING;
gint __GTK_STYLE_PROVIDER_PRIORITY_APPLICATION = GTK_STYLE_PROVIDER_PRIORITY_APPLICATION;
gint __GTK_STYLE_PROVIDER_PRIORITY_FALLBACK = GTK_STYLE_PROVIDER_PRIORITY_FALLBACK;
gint __GTK_STYLE_PROVIDER_PRIORITY_SETTINGS = GTK_STYLE_PROVIDER_PRIORITY_SETTINGS;
gint __GTK_STYLE_PROVIDER_PRIORITY_THEME = GTK_STYLE_PROVIDER_PRIORITY_THEME;
gint __GTK_STYLE_PROVIDER_PRIORITY_USER = GTK_STYLE_PROVIDER_PRIORITY_USER;
gchar* __GTK_STYLE_REGION_COLUMN = GTK_STYLE_REGION_COLUMN;
gchar* __GTK_STYLE_REGION_COLUMN_HEADER = GTK_STYLE_REGION_COLUMN_HEADER;
gchar* __GTK_STYLE_REGION_ROW = GTK_STYLE_REGION_ROW;
gchar* __GTK_STYLE_REGION_TAB = GTK_STYLE_REGION_TAB;
gint __GTK_TEXT_VIEW_PRIORITY_VALIDATE = GTK_TEXT_VIEW_PRIORITY_VALIDATE;
gint __GTK_TREE_SORTABLE_DEFAULT_SORT_COLUMN_ID = GTK_TREE_SORTABLE_DEFAULT_SORT_COLUMN_ID;
gint __GTK_TREE_SORTABLE_UNSORTED_SORT_COLUMN_ID = GTK_TREE_SORTABLE_UNSORTED_SORT_COLUMN_ID;
*/
import "C"

var (
	BINARY_AGE                          = C.__GTK_BINARY_AGE
	INPUT_ERROR                         = C.__GTK_INPUT_ERROR
	INTERFACE_AGE                       = C.__GTK_INTERFACE_AGE
	LEVEL_BAR_OFFSET_HIGH               = C.__GTK_LEVEL_BAR_OFFSET_HIGH
	LEVEL_BAR_OFFSET_LOW                = C.__GTK_LEVEL_BAR_OFFSET_LOW
	MAJOR_VERSION                       = C.__GTK_MAJOR_VERSION
	MAX_COMPOSE_LEN                     = C.__GTK_MAX_COMPOSE_LEN
	MICRO_VERSION                       = C.__GTK_MICRO_VERSION
	MINOR_VERSION                       = C.__GTK_MINOR_VERSION
	PAPER_NAME_A3                       = C.__GTK_PAPER_NAME_A3
	PAPER_NAME_A4                       = C.__GTK_PAPER_NAME_A4
	PAPER_NAME_A5                       = C.__GTK_PAPER_NAME_A5
	PAPER_NAME_B5                       = C.__GTK_PAPER_NAME_B5
	PAPER_NAME_EXECUTIVE                = C.__GTK_PAPER_NAME_EXECUTIVE
	PAPER_NAME_LEGAL                    = C.__GTK_PAPER_NAME_LEGAL
	PAPER_NAME_LETTER                   = C.__GTK_PAPER_NAME_LETTER
	PATH_PRIO_MASK                      = C.__GTK_PATH_PRIO_MASK
	PRINT_SETTINGS_COLLATE              = C.__GTK_PRINT_SETTINGS_COLLATE
	PRINT_SETTINGS_DEFAULT_SOURCE       = C.__GTK_PRINT_SETTINGS_DEFAULT_SOURCE
	PRINT_SETTINGS_DITHER               = C.__GTK_PRINT_SETTINGS_DITHER
	PRINT_SETTINGS_DUPLEX               = C.__GTK_PRINT_SETTINGS_DUPLEX
	PRINT_SETTINGS_FINISHINGS           = C.__GTK_PRINT_SETTINGS_FINISHINGS
	PRINT_SETTINGS_MEDIA_TYPE           = C.__GTK_PRINT_SETTINGS_MEDIA_TYPE
	PRINT_SETTINGS_NUMBER_UP            = C.__GTK_PRINT_SETTINGS_NUMBER_UP
	PRINT_SETTINGS_NUMBER_UP_LAYOUT     = C.__GTK_PRINT_SETTINGS_NUMBER_UP_LAYOUT
	PRINT_SETTINGS_N_COPIES             = C.__GTK_PRINT_SETTINGS_N_COPIES
	PRINT_SETTINGS_ORIENTATION          = C.__GTK_PRINT_SETTINGS_ORIENTATION
	PRINT_SETTINGS_OUTPUT_BASENAME      = C.__GTK_PRINT_SETTINGS_OUTPUT_BASENAME
	PRINT_SETTINGS_OUTPUT_BIN           = C.__GTK_PRINT_SETTINGS_OUTPUT_BIN
	PRINT_SETTINGS_OUTPUT_DIR           = C.__GTK_PRINT_SETTINGS_OUTPUT_DIR
	PRINT_SETTINGS_OUTPUT_FILE_FORMAT   = C.__GTK_PRINT_SETTINGS_OUTPUT_FILE_FORMAT
	PRINT_SETTINGS_OUTPUT_URI           = C.__GTK_PRINT_SETTINGS_OUTPUT_URI
	PRINT_SETTINGS_PAGE_RANGES          = C.__GTK_PRINT_SETTINGS_PAGE_RANGES
	PRINT_SETTINGS_PAGE_SET             = C.__GTK_PRINT_SETTINGS_PAGE_SET
	PRINT_SETTINGS_PAPER_FORMAT         = C.__GTK_PRINT_SETTINGS_PAPER_FORMAT
	PRINT_SETTINGS_PAPER_HEIGHT         = C.__GTK_PRINT_SETTINGS_PAPER_HEIGHT
	PRINT_SETTINGS_PAPER_WIDTH          = C.__GTK_PRINT_SETTINGS_PAPER_WIDTH
	PRINT_SETTINGS_PRINTER              = C.__GTK_PRINT_SETTINGS_PRINTER
	PRINT_SETTINGS_PRINTER_LPI          = C.__GTK_PRINT_SETTINGS_PRINTER_LPI
	PRINT_SETTINGS_PRINT_PAGES          = C.__GTK_PRINT_SETTINGS_PRINT_PAGES
	PRINT_SETTINGS_QUALITY              = C.__GTK_PRINT_SETTINGS_QUALITY
	PRINT_SETTINGS_RESOLUTION           = C.__GTK_PRINT_SETTINGS_RESOLUTION
	PRINT_SETTINGS_RESOLUTION_X         = C.__GTK_PRINT_SETTINGS_RESOLUTION_X
	PRINT_SETTINGS_RESOLUTION_Y         = C.__GTK_PRINT_SETTINGS_RESOLUTION_Y
	PRINT_SETTINGS_REVERSE              = C.__GTK_PRINT_SETTINGS_REVERSE
	PRINT_SETTINGS_SCALE                = C.__GTK_PRINT_SETTINGS_SCALE
	PRINT_SETTINGS_USE_COLOR            = C.__GTK_PRINT_SETTINGS_USE_COLOR
	PRINT_SETTINGS_WIN32_DRIVER_EXTRA   = C.__GTK_PRINT_SETTINGS_WIN32_DRIVER_EXTRA
	PRINT_SETTINGS_WIN32_DRIVER_VERSION = C.__GTK_PRINT_SETTINGS_WIN32_DRIVER_VERSION
	PRIORITY_RESIZE                     = C.__GTK_PRIORITY_RESIZE
	// GTK_STOCK_ABOUT is not generated due to explicit ignore
	// GTK_STOCK_ADD is not generated due to explicit ignore
	// GTK_STOCK_APPLY is not generated due to explicit ignore
	// GTK_STOCK_BOLD is not generated due to explicit ignore
	// GTK_STOCK_CANCEL is not generated due to explicit ignore
	// GTK_STOCK_CAPS_LOCK_WARNING is not generated due to explicit ignore
	// GTK_STOCK_CDROM is not generated due to explicit ignore
	// GTK_STOCK_CLEAR is not generated due to explicit ignore
	// GTK_STOCK_CLOSE is not generated due to explicit ignore
	// GTK_STOCK_COLOR_PICKER is not generated due to explicit ignore
	// GTK_STOCK_CONNECT is not generated due to explicit ignore
	// GTK_STOCK_CONVERT is not generated due to explicit ignore
	// GTK_STOCK_COPY is not generated due to explicit ignore
	// GTK_STOCK_CUT is not generated due to explicit ignore
	// GTK_STOCK_DELETE is not generated due to explicit ignore
	// GTK_STOCK_DIALOG_AUTHENTICATION is not generated due to explicit ignore
	// GTK_STOCK_DIALOG_ERROR is not generated due to explicit ignore
	// GTK_STOCK_DIALOG_INFO is not generated due to explicit ignore
	// GTK_STOCK_DIALOG_QUESTION is not generated due to explicit ignore
	// GTK_STOCK_DIALOG_WARNING is not generated due to explicit ignore
	// GTK_STOCK_DIRECTORY is not generated due to explicit ignore
	// GTK_STOCK_DISCARD is not generated due to explicit ignore
	// GTK_STOCK_DISCONNECT is not generated due to explicit ignore
	// GTK_STOCK_DND is not generated due to explicit ignore
	// GTK_STOCK_DND_MULTIPLE is not generated due to explicit ignore
	// GTK_STOCK_EDIT is not generated due to explicit ignore
	// GTK_STOCK_EXECUTE is not generated due to explicit ignore
	// GTK_STOCK_FILE is not generated due to explicit ignore
	// GTK_STOCK_FIND is not generated due to explicit ignore
	// GTK_STOCK_FIND_AND_REPLACE is not generated due to explicit ignore
	// GTK_STOCK_FLOPPY is not generated due to explicit ignore
	// GTK_STOCK_FULLSCREEN is not generated due to explicit ignore
	// GTK_STOCK_GOTO_BOTTOM is not generated due to explicit ignore
	// GTK_STOCK_GOTO_FIRST is not generated due to explicit ignore
	// GTK_STOCK_GOTO_LAST is not generated due to explicit ignore
	// GTK_STOCK_GOTO_TOP is not generated due to explicit ignore
	// GTK_STOCK_GO_BACK is not generated due to explicit ignore
	// GTK_STOCK_GO_DOWN is not generated due to explicit ignore
	// GTK_STOCK_GO_FORWARD is not generated due to explicit ignore
	// GTK_STOCK_GO_UP is not generated due to explicit ignore
	// GTK_STOCK_HARDDISK is not generated due to explicit ignore
	// GTK_STOCK_HELP is not generated due to explicit ignore
	// GTK_STOCK_HOME is not generated due to explicit ignore
	// GTK_STOCK_INDENT is not generated due to explicit ignore
	// GTK_STOCK_INDEX is not generated due to explicit ignore
	// GTK_STOCK_INFO is not generated due to explicit ignore
	// GTK_STOCK_ITALIC is not generated due to explicit ignore
	// GTK_STOCK_JUMP_TO is not generated due to explicit ignore
	// GTK_STOCK_JUSTIFY_CENTER is not generated due to explicit ignore
	// GTK_STOCK_JUSTIFY_FILL is not generated due to explicit ignore
	// GTK_STOCK_JUSTIFY_LEFT is not generated due to explicit ignore
	// GTK_STOCK_JUSTIFY_RIGHT is not generated due to explicit ignore
	// GTK_STOCK_LEAVE_FULLSCREEN is not generated due to explicit ignore
	// GTK_STOCK_MEDIA_FORWARD is not generated due to explicit ignore
	// GTK_STOCK_MEDIA_NEXT is not generated due to explicit ignore
	// GTK_STOCK_MEDIA_PAUSE is not generated due to explicit ignore
	// GTK_STOCK_MEDIA_PLAY is not generated due to explicit ignore
	// GTK_STOCK_MEDIA_PREVIOUS is not generated due to explicit ignore
	// GTK_STOCK_MEDIA_RECORD is not generated due to explicit ignore
	// GTK_STOCK_MEDIA_REWIND is not generated due to explicit ignore
	// GTK_STOCK_MEDIA_STOP is not generated due to explicit ignore
	// GTK_STOCK_MISSING_IMAGE is not generated due to explicit ignore
	// GTK_STOCK_NETWORK is not generated due to explicit ignore
	// GTK_STOCK_NEW is not generated due to explicit ignore
	// GTK_STOCK_NO is not generated due to explicit ignore
	// GTK_STOCK_OK is not generated due to explicit ignore
	// GTK_STOCK_OPEN is not generated due to explicit ignore
	// GTK_STOCK_ORIENTATION_LANDSCAPE is not generated due to explicit ignore
	// GTK_STOCK_ORIENTATION_PORTRAIT is not generated due to explicit ignore
	// GTK_STOCK_ORIENTATION_REVERSE_LANDSCAPE is not generated due to explicit ignore
	// GTK_STOCK_ORIENTATION_REVERSE_PORTRAIT is not generated due to explicit ignore
	// GTK_STOCK_PAGE_SETUP is not generated due to explicit ignore
	// GTK_STOCK_PASTE is not generated due to explicit ignore
	// GTK_STOCK_PREFERENCES is not generated due to explicit ignore
	// GTK_STOCK_PRINT is not generated due to explicit ignore
	// GTK_STOCK_PRINT_ERROR is not generated due to explicit ignore
	// GTK_STOCK_PRINT_PAUSED is not generated due to explicit ignore
	// GTK_STOCK_PRINT_PREVIEW is not generated due to explicit ignore
	// GTK_STOCK_PRINT_REPORT is not generated due to explicit ignore
	// GTK_STOCK_PRINT_WARNING is not generated due to explicit ignore
	// GTK_STOCK_PROPERTIES is not generated due to explicit ignore
	// GTK_STOCK_QUIT is not generated due to explicit ignore
	// GTK_STOCK_REDO is not generated due to explicit ignore
	// GTK_STOCK_REFRESH is not generated due to explicit ignore
	// GTK_STOCK_REMOVE is not generated due to explicit ignore
	// GTK_STOCK_REVERT_TO_SAVED is not generated due to explicit ignore
	// GTK_STOCK_SAVE is not generated due to explicit ignore
	// GTK_STOCK_SAVE_AS is not generated due to explicit ignore
	// GTK_STOCK_SELECT_ALL is not generated due to explicit ignore
	// GTK_STOCK_SELECT_COLOR is not generated due to explicit ignore
	// GTK_STOCK_SELECT_FONT is not generated due to explicit ignore
	// GTK_STOCK_SORT_ASCENDING is not generated due to explicit ignore
	// GTK_STOCK_SORT_DESCENDING is not generated due to explicit ignore
	// GTK_STOCK_SPELL_CHECK is not generated due to explicit ignore
	// GTK_STOCK_STOP is not generated due to explicit ignore
	// GTK_STOCK_STRIKETHROUGH is not generated due to explicit ignore
	// GTK_STOCK_UNDELETE is not generated due to explicit ignore
	// GTK_STOCK_UNDERLINE is not generated due to explicit ignore
	// GTK_STOCK_UNDO is not generated due to explicit ignore
	// GTK_STOCK_UNINDENT is not generated due to explicit ignore
	// GTK_STOCK_YES is not generated due to explicit ignore
	// GTK_STOCK_ZOOM_100 is not generated due to explicit ignore
	// GTK_STOCK_ZOOM_FIT is not generated due to explicit ignore
	// GTK_STOCK_ZOOM_IN is not generated due to explicit ignore
	// GTK_STOCK_ZOOM_OUT is not generated due to explicit ignore
	STYLE_CLASS_ACCELERATOR               = C.__GTK_STYLE_CLASS_ACCELERATOR
	STYLE_CLASS_ARROW                     = C.__GTK_STYLE_CLASS_ARROW
	STYLE_CLASS_BACKGROUND                = C.__GTK_STYLE_CLASS_BACKGROUND
	STYLE_CLASS_BOTTOM                    = C.__GTK_STYLE_CLASS_BOTTOM
	STYLE_CLASS_BUTTON                    = C.__GTK_STYLE_CLASS_BUTTON
	STYLE_CLASS_CALENDAR                  = C.__GTK_STYLE_CLASS_CALENDAR
	STYLE_CLASS_CELL                      = C.__GTK_STYLE_CLASS_CELL
	STYLE_CLASS_CHECK                     = C.__GTK_STYLE_CLASS_CHECK
	STYLE_CLASS_COMBOBOX_ENTRY            = C.__GTK_STYLE_CLASS_COMBOBOX_ENTRY
	STYLE_CLASS_CONTEXT_MENU              = C.__GTK_STYLE_CLASS_CONTEXT_MENU
	STYLE_CLASS_CURSOR_HANDLE             = C.__GTK_STYLE_CLASS_CURSOR_HANDLE
	STYLE_CLASS_DEFAULT                   = C.__GTK_STYLE_CLASS_DEFAULT
	STYLE_CLASS_DESTRUCTIVE_ACTION        = C.__GTK_STYLE_CLASS_DESTRUCTIVE_ACTION
	STYLE_CLASS_DIM_LABEL                 = C.__GTK_STYLE_CLASS_DIM_LABEL
	STYLE_CLASS_DND                       = C.__GTK_STYLE_CLASS_DND
	STYLE_CLASS_DOCK                      = C.__GTK_STYLE_CLASS_DOCK
	STYLE_CLASS_ENTRY                     = C.__GTK_STYLE_CLASS_ENTRY
	STYLE_CLASS_ERROR                     = C.__GTK_STYLE_CLASS_ERROR
	STYLE_CLASS_EXPANDER                  = C.__GTK_STYLE_CLASS_EXPANDER
	STYLE_CLASS_FRAME                     = C.__GTK_STYLE_CLASS_FRAME
	STYLE_CLASS_GRIP                      = C.__GTK_STYLE_CLASS_GRIP
	STYLE_CLASS_HEADER                    = C.__GTK_STYLE_CLASS_HEADER
	STYLE_CLASS_HIGHLIGHT                 = C.__GTK_STYLE_CLASS_HIGHLIGHT
	STYLE_CLASS_HORIZONTAL                = C.__GTK_STYLE_CLASS_HORIZONTAL
	STYLE_CLASS_IMAGE                     = C.__GTK_STYLE_CLASS_IMAGE
	STYLE_CLASS_INFO                      = C.__GTK_STYLE_CLASS_INFO
	STYLE_CLASS_INLINE_TOOLBAR            = C.__GTK_STYLE_CLASS_INLINE_TOOLBAR
	STYLE_CLASS_INSERTION_CURSOR          = C.__GTK_STYLE_CLASS_INSERTION_CURSOR
	STYLE_CLASS_LEFT                      = C.__GTK_STYLE_CLASS_LEFT
	STYLE_CLASS_LEVEL_BAR                 = C.__GTK_STYLE_CLASS_LEVEL_BAR
	STYLE_CLASS_LINKED                    = C.__GTK_STYLE_CLASS_LINKED
	STYLE_CLASS_LIST                      = C.__GTK_STYLE_CLASS_LIST
	STYLE_CLASS_LIST_ROW                  = C.__GTK_STYLE_CLASS_LIST_ROW
	STYLE_CLASS_MARK                      = C.__GTK_STYLE_CLASS_MARK
	STYLE_CLASS_MENU                      = C.__GTK_STYLE_CLASS_MENU
	STYLE_CLASS_MENUBAR                   = C.__GTK_STYLE_CLASS_MENUBAR
	STYLE_CLASS_MENUITEM                  = C.__GTK_STYLE_CLASS_MENUITEM
	STYLE_CLASS_NEEDS_ATTENTION           = C.__GTK_STYLE_CLASS_NEEDS_ATTENTION
	STYLE_CLASS_NOTEBOOK                  = C.__GTK_STYLE_CLASS_NOTEBOOK
	STYLE_CLASS_OSD                       = C.__GTK_STYLE_CLASS_OSD
	STYLE_CLASS_PANE_SEPARATOR            = C.__GTK_STYLE_CLASS_PANE_SEPARATOR
	STYLE_CLASS_PRIMARY_TOOLBAR           = C.__GTK_STYLE_CLASS_PRIMARY_TOOLBAR
	STYLE_CLASS_PROGRESSBAR               = C.__GTK_STYLE_CLASS_PROGRESSBAR
	STYLE_CLASS_PULSE                     = C.__GTK_STYLE_CLASS_PULSE
	STYLE_CLASS_QUESTION                  = C.__GTK_STYLE_CLASS_QUESTION
	STYLE_CLASS_RADIO                     = C.__GTK_STYLE_CLASS_RADIO
	STYLE_CLASS_RAISED                    = C.__GTK_STYLE_CLASS_RAISED
	STYLE_CLASS_READ_ONLY                 = C.__GTK_STYLE_CLASS_READ_ONLY
	STYLE_CLASS_RIGHT                     = C.__GTK_STYLE_CLASS_RIGHT
	STYLE_CLASS_RUBBERBAND                = C.__GTK_STYLE_CLASS_RUBBERBAND
	STYLE_CLASS_SCALE                     = C.__GTK_STYLE_CLASS_SCALE
	STYLE_CLASS_SCALE_HAS_MARKS_ABOVE     = C.__GTK_STYLE_CLASS_SCALE_HAS_MARKS_ABOVE
	STYLE_CLASS_SCALE_HAS_MARKS_BELOW     = C.__GTK_STYLE_CLASS_SCALE_HAS_MARKS_BELOW
	STYLE_CLASS_SCROLLBAR                 = C.__GTK_STYLE_CLASS_SCROLLBAR
	STYLE_CLASS_SCROLLBARS_JUNCTION       = C.__GTK_STYLE_CLASS_SCROLLBARS_JUNCTION
	STYLE_CLASS_SEPARATOR                 = C.__GTK_STYLE_CLASS_SEPARATOR
	STYLE_CLASS_SIDEBAR                   = C.__GTK_STYLE_CLASS_SIDEBAR
	STYLE_CLASS_SLIDER                    = C.__GTK_STYLE_CLASS_SLIDER
	STYLE_CLASS_SPINBUTTON                = C.__GTK_STYLE_CLASS_SPINBUTTON
	STYLE_CLASS_SPINNER                   = C.__GTK_STYLE_CLASS_SPINNER
	STYLE_CLASS_SUGGESTED_ACTION          = C.__GTK_STYLE_CLASS_SUGGESTED_ACTION
	STYLE_CLASS_TITLEBAR                  = C.__GTK_STYLE_CLASS_TITLEBAR
	STYLE_CLASS_TOOLBAR                   = C.__GTK_STYLE_CLASS_TOOLBAR
	STYLE_CLASS_TOOLTIP                   = C.__GTK_STYLE_CLASS_TOOLTIP
	STYLE_CLASS_TOP                       = C.__GTK_STYLE_CLASS_TOP
	STYLE_CLASS_TROUGH                    = C.__GTK_STYLE_CLASS_TROUGH
	STYLE_CLASS_VERTICAL                  = C.__GTK_STYLE_CLASS_VERTICAL
	STYLE_CLASS_VIEW                      = C.__GTK_STYLE_CLASS_VIEW
	STYLE_CLASS_WARNING                   = C.__GTK_STYLE_CLASS_WARNING
	STYLE_PROPERTY_BACKGROUND_COLOR       = C.__GTK_STYLE_PROPERTY_BACKGROUND_COLOR
	STYLE_PROPERTY_BACKGROUND_IMAGE       = C.__GTK_STYLE_PROPERTY_BACKGROUND_IMAGE
	STYLE_PROPERTY_BORDER_COLOR           = C.__GTK_STYLE_PROPERTY_BORDER_COLOR
	STYLE_PROPERTY_BORDER_RADIUS          = C.__GTK_STYLE_PROPERTY_BORDER_RADIUS
	STYLE_PROPERTY_BORDER_STYLE           = C.__GTK_STYLE_PROPERTY_BORDER_STYLE
	STYLE_PROPERTY_BORDER_WIDTH           = C.__GTK_STYLE_PROPERTY_BORDER_WIDTH
	STYLE_PROPERTY_COLOR                  = C.__GTK_STYLE_PROPERTY_COLOR
	STYLE_PROPERTY_FONT                   = C.__GTK_STYLE_PROPERTY_FONT
	STYLE_PROPERTY_MARGIN                 = C.__GTK_STYLE_PROPERTY_MARGIN
	STYLE_PROPERTY_PADDING                = C.__GTK_STYLE_PROPERTY_PADDING
	STYLE_PROVIDER_PRIORITY_APPLICATION   = C.__GTK_STYLE_PROVIDER_PRIORITY_APPLICATION
	STYLE_PROVIDER_PRIORITY_FALLBACK      = C.__GTK_STYLE_PROVIDER_PRIORITY_FALLBACK
	STYLE_PROVIDER_PRIORITY_SETTINGS      = C.__GTK_STYLE_PROVIDER_PRIORITY_SETTINGS
	STYLE_PROVIDER_PRIORITY_THEME         = C.__GTK_STYLE_PROVIDER_PRIORITY_THEME
	STYLE_PROVIDER_PRIORITY_USER          = C.__GTK_STYLE_PROVIDER_PRIORITY_USER
	STYLE_REGION_COLUMN                   = C.__GTK_STYLE_REGION_COLUMN
	STYLE_REGION_COLUMN_HEADER            = C.__GTK_STYLE_REGION_COLUMN_HEADER
	STYLE_REGION_ROW                      = C.__GTK_STYLE_REGION_ROW
	STYLE_REGION_TAB                      = C.__GTK_STYLE_REGION_TAB
	TEXT_VIEW_PRIORITY_VALIDATE           = C.__GTK_TEXT_VIEW_PRIORITY_VALIDATE
	TREE_SORTABLE_DEFAULT_SORT_COLUMN_ID  = C.__GTK_TREE_SORTABLE_DEFAULT_SORT_COLUMN_ID
	TREE_SORTABLE_UNSORTED_SORT_COLUMN_ID = C.__GTK_TREE_SORTABLE_UNSORTED_SORT_COLUMN_ID
)
