package gtk

/*
#include <gtk/gtk.h>
#include <gtk/gtkx.h>
#include <stdlib.h>
*/
import "C"

var (
	// AccelFlags
	ACCEL_VISIBLE = C.GtkAccelFlags(C.GTK_ACCEL_VISIBLE)
	ACCEL_LOCKED  = C.GtkAccelFlags(C.GTK_ACCEL_LOCKED)
	ACCEL_MASK    = C.GtkAccelFlags(C.GTK_ACCEL_MASK)

	// ApplicationInhibitFlags
	APPLICATION_INHIBIT_LOGOUT  = C.GtkApplicationInhibitFlags(C.GTK_APPLICATION_INHIBIT_LOGOUT)
	APPLICATION_INHIBIT_SWITCH  = C.GtkApplicationInhibitFlags(C.GTK_APPLICATION_INHIBIT_SWITCH)
	APPLICATION_INHIBIT_SUSPEND = C.GtkApplicationInhibitFlags(C.GTK_APPLICATION_INHIBIT_SUSPEND)
	APPLICATION_INHIBIT_IDLE    = C.GtkApplicationInhibitFlags(C.GTK_APPLICATION_INHIBIT_IDLE)

	// AttachOptions
	EXPAND = C.GtkAttachOptions(C.GTK_EXPAND)
	SHRINK = C.GtkAttachOptions(C.GTK_SHRINK)
	FILL   = C.GtkAttachOptions(C.GTK_FILL)

	// CalendarDisplayOptions
	CALENDAR_SHOW_HEADING      = C.GtkCalendarDisplayOptions(C.GTK_CALENDAR_SHOW_HEADING)
	CALENDAR_SHOW_DAY_NAMES    = C.GtkCalendarDisplayOptions(C.GTK_CALENDAR_SHOW_DAY_NAMES)
	CALENDAR_NO_MONTH_CHANGE   = C.GtkCalendarDisplayOptions(C.GTK_CALENDAR_NO_MONTH_CHANGE)
	CALENDAR_SHOW_WEEK_NUMBERS = C.GtkCalendarDisplayOptions(C.GTK_CALENDAR_SHOW_WEEK_NUMBERS)
	CALENDAR_SHOW_DETAILS      = C.GtkCalendarDisplayOptions(C.GTK_CALENDAR_SHOW_DETAILS)

	// CellRendererState
	CELL_RENDERER_SELECTED    = C.GtkCellRendererState(C.GTK_CELL_RENDERER_SELECTED)
	CELL_RENDERER_PRELIT      = C.GtkCellRendererState(C.GTK_CELL_RENDERER_PRELIT)
	CELL_RENDERER_INSENSITIVE = C.GtkCellRendererState(C.GTK_CELL_RENDERER_INSENSITIVE)
	CELL_RENDERER_SORTED      = C.GtkCellRendererState(C.GTK_CELL_RENDERER_SORTED)
	CELL_RENDERER_FOCUSED     = C.GtkCellRendererState(C.GTK_CELL_RENDERER_FOCUSED)
	CELL_RENDERER_EXPANDABLE  = C.GtkCellRendererState(C.GTK_CELL_RENDERER_EXPANDABLE)
	CELL_RENDERER_EXPANDED    = C.GtkCellRendererState(C.GTK_CELL_RENDERER_EXPANDED)

	// DebugFlag
	DEBUG_MISC           = C.GtkDebugFlag(C.GTK_DEBUG_MISC)
	DEBUG_PLUGSOCKET     = C.GtkDebugFlag(C.GTK_DEBUG_PLUGSOCKET)
	DEBUG_TEXT           = C.GtkDebugFlag(C.GTK_DEBUG_TEXT)
	DEBUG_TREE           = C.GtkDebugFlag(C.GTK_DEBUG_TREE)
	DEBUG_UPDATES        = C.GtkDebugFlag(C.GTK_DEBUG_UPDATES)
	DEBUG_KEYBINDINGS    = C.GtkDebugFlag(C.GTK_DEBUG_KEYBINDINGS)
	DEBUG_MULTIHEAD      = C.GtkDebugFlag(C.GTK_DEBUG_MULTIHEAD)
	DEBUG_MODULES        = C.GtkDebugFlag(C.GTK_DEBUG_MODULES)
	DEBUG_GEOMETRY       = C.GtkDebugFlag(C.GTK_DEBUG_GEOMETRY)
	DEBUG_ICONTHEME      = C.GtkDebugFlag(C.GTK_DEBUG_ICONTHEME)
	DEBUG_PRINTING       = C.GtkDebugFlag(C.GTK_DEBUG_PRINTING)
	DEBUG_BUILDER        = C.GtkDebugFlag(C.GTK_DEBUG_BUILDER)
	DEBUG_SIZE_REQUEST   = C.GtkDebugFlag(C.GTK_DEBUG_SIZE_REQUEST)
	DEBUG_NO_CSS_CACHE   = C.GtkDebugFlag(C.GTK_DEBUG_NO_CSS_CACHE)
	DEBUG_BASELINES      = C.GtkDebugFlag(C.GTK_DEBUG_BASELINES)
	DEBUG_PIXEL_CACHE    = C.GtkDebugFlag(C.GTK_DEBUG_PIXEL_CACHE)
	DEBUG_NO_PIXEL_CACHE = C.GtkDebugFlag(C.GTK_DEBUG_NO_PIXEL_CACHE)

	// DestDefaults
	DEST_DEFAULT_MOTION    = C.GtkDestDefaults(C.GTK_DEST_DEFAULT_MOTION)
	DEST_DEFAULT_HIGHLIGHT = C.GtkDestDefaults(C.GTK_DEST_DEFAULT_HIGHLIGHT)
	DEST_DEFAULT_DROP      = C.GtkDestDefaults(C.GTK_DEST_DEFAULT_DROP)
	DEST_DEFAULT_ALL       = C.GtkDestDefaults(C.GTK_DEST_DEFAULT_ALL)

	// DialogFlags
	DIALOG_MODAL               = C.GtkDialogFlags(C.GTK_DIALOG_MODAL)
	DIALOG_DESTROY_WITH_PARENT = C.GtkDialogFlags(C.GTK_DIALOG_DESTROY_WITH_PARENT)
	DIALOG_USE_HEADER_BAR      = C.GtkDialogFlags(C.GTK_DIALOG_USE_HEADER_BAR)

	// FileFilterFlags
	FILE_FILTER_FILENAME     = C.GtkFileFilterFlags(C.GTK_FILE_FILTER_FILENAME)
	FILE_FILTER_URI          = C.GtkFileFilterFlags(C.GTK_FILE_FILTER_URI)
	FILE_FILTER_DISPLAY_NAME = C.GtkFileFilterFlags(C.GTK_FILE_FILTER_DISPLAY_NAME)
	FILE_FILTER_MIME_TYPE    = C.GtkFileFilterFlags(C.GTK_FILE_FILTER_MIME_TYPE)

	// IconLookupFlags
	ICON_LOOKUP_NO_SVG           = C.GtkIconLookupFlags(C.GTK_ICON_LOOKUP_NO_SVG)
	ICON_LOOKUP_FORCE_SVG        = C.GtkIconLookupFlags(C.GTK_ICON_LOOKUP_FORCE_SVG)
	ICON_LOOKUP_USE_BUILTIN      = C.GtkIconLookupFlags(C.GTK_ICON_LOOKUP_USE_BUILTIN)
	ICON_LOOKUP_GENERIC_FALLBACK = C.GtkIconLookupFlags(C.GTK_ICON_LOOKUP_GENERIC_FALLBACK)
	ICON_LOOKUP_FORCE_SIZE       = C.GtkIconLookupFlags(C.GTK_ICON_LOOKUP_FORCE_SIZE)

	// InputHints
	INPUT_HINT_NONE                = C.GtkInputHints(C.GTK_INPUT_HINT_NONE)
	INPUT_HINT_SPELLCHECK          = C.GtkInputHints(C.GTK_INPUT_HINT_SPELLCHECK)
	INPUT_HINT_NO_SPELLCHECK       = C.GtkInputHints(C.GTK_INPUT_HINT_NO_SPELLCHECK)
	INPUT_HINT_WORD_COMPLETION     = C.GtkInputHints(C.GTK_INPUT_HINT_WORD_COMPLETION)
	INPUT_HINT_LOWERCASE           = C.GtkInputHints(C.GTK_INPUT_HINT_LOWERCASE)
	INPUT_HINT_UPPERCASE_CHARS     = C.GtkInputHints(C.GTK_INPUT_HINT_UPPERCASE_CHARS)
	INPUT_HINT_UPPERCASE_WORDS     = C.GtkInputHints(C.GTK_INPUT_HINT_UPPERCASE_WORDS)
	INPUT_HINT_UPPERCASE_SENTENCES = C.GtkInputHints(C.GTK_INPUT_HINT_UPPERCASE_SENTENCES)
	INPUT_HINT_INHIBIT_OSK         = C.GtkInputHints(C.GTK_INPUT_HINT_INHIBIT_OSK)

	// JunctionSides
	JUNCTION_NONE               = C.GtkJunctionSides(C.GTK_JUNCTION_NONE)
	JUNCTION_CORNER_TOPLEFT     = C.GtkJunctionSides(C.GTK_JUNCTION_CORNER_TOPLEFT)
	JUNCTION_CORNER_TOPRIGHT    = C.GtkJunctionSides(C.GTK_JUNCTION_CORNER_TOPRIGHT)
	JUNCTION_CORNER_BOTTOMLEFT  = C.GtkJunctionSides(C.GTK_JUNCTION_CORNER_BOTTOMLEFT)
	JUNCTION_CORNER_BOTTOMRIGHT = C.GtkJunctionSides(C.GTK_JUNCTION_CORNER_BOTTOMRIGHT)
	JUNCTION_TOP                = C.GtkJunctionSides(C.GTK_JUNCTION_TOP)
	JUNCTION_BOTTOM             = C.GtkJunctionSides(C.GTK_JUNCTION_BOTTOM)
	JUNCTION_LEFT               = C.GtkJunctionSides(C.GTK_JUNCTION_LEFT)
	JUNCTION_RIGHT              = C.GtkJunctionSides(C.GTK_JUNCTION_RIGHT)

	// PlacesOpenFlags
	PLACES_OPEN_NORMAL     = C.GtkPlacesOpenFlags(C.GTK_PLACES_OPEN_NORMAL)
	PLACES_OPEN_NEW_TAB    = C.GtkPlacesOpenFlags(C.GTK_PLACES_OPEN_NEW_TAB)
	PLACES_OPEN_NEW_WINDOW = C.GtkPlacesOpenFlags(C.GTK_PLACES_OPEN_NEW_WINDOW)

	// RcFlags
	RC_FG   = C.GtkRcFlags(C.GTK_RC_FG)
	RC_BG   = C.GtkRcFlags(C.GTK_RC_BG)
	RC_TEXT = C.GtkRcFlags(C.GTK_RC_TEXT)
	RC_BASE = C.GtkRcFlags(C.GTK_RC_BASE)

	// RecentFilterFlags
	RECENT_FILTER_URI          = C.GtkRecentFilterFlags(C.GTK_RECENT_FILTER_URI)
	RECENT_FILTER_DISPLAY_NAME = C.GtkRecentFilterFlags(C.GTK_RECENT_FILTER_DISPLAY_NAME)
	RECENT_FILTER_MIME_TYPE    = C.GtkRecentFilterFlags(C.GTK_RECENT_FILTER_MIME_TYPE)
	RECENT_FILTER_APPLICATION  = C.GtkRecentFilterFlags(C.GTK_RECENT_FILTER_APPLICATION)
	RECENT_FILTER_GROUP        = C.GtkRecentFilterFlags(C.GTK_RECENT_FILTER_GROUP)
	RECENT_FILTER_AGE          = C.GtkRecentFilterFlags(C.GTK_RECENT_FILTER_AGE)

	// RegionFlags
	REGION_EVEN   = C.GtkRegionFlags(C.GTK_REGION_EVEN)
	REGION_ODD    = C.GtkRegionFlags(C.GTK_REGION_ODD)
	REGION_FIRST  = C.GtkRegionFlags(C.GTK_REGION_FIRST)
	REGION_LAST   = C.GtkRegionFlags(C.GTK_REGION_LAST)
	REGION_ONLY   = C.GtkRegionFlags(C.GTK_REGION_ONLY)
	REGION_SORTED = C.GtkRegionFlags(C.GTK_REGION_SORTED)

	// StateFlags
	STATE_FLAG_NORMAL       = C.GtkStateFlags(C.GTK_STATE_FLAG_NORMAL)
	STATE_FLAG_ACTIVE       = C.GtkStateFlags(C.GTK_STATE_FLAG_ACTIVE)
	STATE_FLAG_PRELIGHT     = C.GtkStateFlags(C.GTK_STATE_FLAG_PRELIGHT)
	STATE_FLAG_SELECTED     = C.GtkStateFlags(C.GTK_STATE_FLAG_SELECTED)
	STATE_FLAG_INSENSITIVE  = C.GtkStateFlags(C.GTK_STATE_FLAG_INSENSITIVE)
	STATE_FLAG_INCONSISTENT = C.GtkStateFlags(C.GTK_STATE_FLAG_INCONSISTENT)
	STATE_FLAG_FOCUSED      = C.GtkStateFlags(C.GTK_STATE_FLAG_FOCUSED)
	STATE_FLAG_BACKDROP     = C.GtkStateFlags(C.GTK_STATE_FLAG_BACKDROP)
	STATE_FLAG_DIR_LTR      = C.GtkStateFlags(C.GTK_STATE_FLAG_DIR_LTR)
	STATE_FLAG_DIR_RTL      = C.GtkStateFlags(C.GTK_STATE_FLAG_DIR_RTL)
	STATE_FLAG_LINK         = C.GtkStateFlags(C.GTK_STATE_FLAG_LINK)
	STATE_FLAG_VISITED      = C.GtkStateFlags(C.GTK_STATE_FLAG_VISITED)

	// TargetFlags
	TARGET_SAME_APP     = C.GtkTargetFlags(C.GTK_TARGET_SAME_APP)
	TARGET_SAME_WIDGET  = C.GtkTargetFlags(C.GTK_TARGET_SAME_WIDGET)
	TARGET_OTHER_APP    = C.GtkTargetFlags(C.GTK_TARGET_OTHER_APP)
	TARGET_OTHER_WIDGET = C.GtkTargetFlags(C.GTK_TARGET_OTHER_WIDGET)

	// TextSearchFlags
	TEXT_SEARCH_VISIBLE_ONLY     = C.GtkTextSearchFlags(C.GTK_TEXT_SEARCH_VISIBLE_ONLY)
	TEXT_SEARCH_TEXT_ONLY        = C.GtkTextSearchFlags(C.GTK_TEXT_SEARCH_TEXT_ONLY)
	TEXT_SEARCH_CASE_INSENSITIVE = C.GtkTextSearchFlags(C.GTK_TEXT_SEARCH_CASE_INSENSITIVE)

	// ToolPaletteDragTargets
	TOOL_PALETTE_DRAG_ITEMS  = C.GtkToolPaletteDragTargets(C.GTK_TOOL_PALETTE_DRAG_ITEMS)
	TOOL_PALETTE_DRAG_GROUPS = C.GtkToolPaletteDragTargets(C.GTK_TOOL_PALETTE_DRAG_GROUPS)

	// TreeModelFlags
	TREE_MODEL_ITERS_PERSIST = C.GtkTreeModelFlags(C.GTK_TREE_MODEL_ITERS_PERSIST)
	TREE_MODEL_LIST_ONLY     = C.GtkTreeModelFlags(C.GTK_TREE_MODEL_LIST_ONLY)

	// UIManagerItemType
	UI_MANAGER_AUTO              = C.GtkUIManagerItemType(C.GTK_UI_MANAGER_AUTO)
	UI_MANAGER_MENUBAR           = C.GtkUIManagerItemType(C.GTK_UI_MANAGER_MENUBAR)
	UI_MANAGER_MENU              = C.GtkUIManagerItemType(C.GTK_UI_MANAGER_MENU)
	UI_MANAGER_TOOLBAR           = C.GtkUIManagerItemType(C.GTK_UI_MANAGER_TOOLBAR)
	UI_MANAGER_PLACEHOLDER       = C.GtkUIManagerItemType(C.GTK_UI_MANAGER_PLACEHOLDER)
	UI_MANAGER_POPUP             = C.GtkUIManagerItemType(C.GTK_UI_MANAGER_POPUP)
	UI_MANAGER_MENUITEM          = C.GtkUIManagerItemType(C.GTK_UI_MANAGER_MENUITEM)
	UI_MANAGER_TOOLITEM          = C.GtkUIManagerItemType(C.GTK_UI_MANAGER_TOOLITEM)
	UI_MANAGER_SEPARATOR         = C.GtkUIManagerItemType(C.GTK_UI_MANAGER_SEPARATOR)
	UI_MANAGER_ACCELERATOR       = C.GtkUIManagerItemType(C.GTK_UI_MANAGER_ACCELERATOR)
	UI_MANAGER_POPUP_WITH_ACCELS = C.GtkUIManagerItemType(C.GTK_UI_MANAGER_POPUP_WITH_ACCELS)
)
